

import type { Risk, BowtieData, BowtieThreat, BowtieConsequence, Control, Kpi, EscalationRule } from './types';
import { identifiedRisksData } from './identified-risks-data';

export const kpisData: Kpi[] = [
    { id: "KPI-1", controlId: 1, frequencia: "Mensal", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-07-30", diasPendentes: -25, status: "Pendente", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-2", controlId: 2, frequencia: "Mensal", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-08-01", diasPendentes: -27, status: "Atrasado", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-3", controlId: 3, frequencia: "Semestral", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-12-28", diasPendentes: -146, status: "Pendente", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-4", controlId: 4, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-5", controlId: 5, frequencia: "Mensal", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-07-29", diasPendentes: -24, status: "Pendente", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-6", controlId: 6, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" },
    { id: "KPI-7", controlId: 7, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Bruno Edison Silva Dalosto", emailResponsavel: "bruno.dalosto@rumolog.com" },
    { id: "KPI-8", controlId: 8, frequencia: "Mensal", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-08-01", diasPendentes: -27, status: "Atrasado", responsavel: "Bruno Edison Silva Dalosto", emailResponsavel: "bruno.dalosto@rumolog.com" },
    { id: "KPI-9", controlId: 9, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-10", controlId: 10, frequencia: "Mensal", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-08-01", diasPendentes: -27, status: "Atrasado", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-11", controlId: 11, frequencia: "Mensal", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-07-30", diasPendentes: -25, status: "Pendente", responsavel: "Victor Dimitri Zolotareff", emailResponsavel: "victor.zolotareff@rumolog.com" },
    { id: "KPI-12", controlId: 12, frequencia: "Semestral", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-12-28", diasPendentes: -146, status: "Pendente", responsavel: "Victor Dimitri Zolotareff", emailResponsavel: "victor.zolotareff@rumolog.com" },
    { id: "KPI-13", controlId: 13, frequencia: "Trimestral", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-10-01", diasPendentes: -88, status: "Atrasado", responsavel: "Bruno Edison Silva Dalosto", emailResponsavel: "bruno.dalosto@rumolog.com" },
    { id: "KPI-14", controlId: 14, frequencia: "Mensal", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-07-30", diasPendentes: -25, status: "Pendente", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-15", controlId: 15, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-16", controlId: 16, frequencia: "Trimestral", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-09-30", diasPendentes: -87, status: "Pendente", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-17", controlId: 17, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" },
    { id: "KPI-18", controlId: 18, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Bruno Edison Silva Dalosto", emailResponsavel: "bruno.dalosto@rumolog.com" },
    { id: "KPI-19", controlId: 19, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-20", controlId: 20, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Victor Dimitri Zolotareff", emailResponsavel: "victor.zolotareff@rumolog.com" },
    { id: "KPI-21", controlId: 21, frequencia: "Mensal", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-08-01", diasPendentes: -27, status: "Atrasado", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-22", controlId: 22, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Victor Dimitri Zolotareff", emailResponsavel: "victor.zolotareff@rumolog.com" },
    { id: "KPI-23", controlId: 23, frequencia: "Mensal", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-08-01", diasPendentes: -27, status: "Atrasado", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" },
    { id: "KPI-24", controlId: 24, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" },
    { id: "KPI-25", controlId: 25, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" },
    { id: "KPI-26", controlId: 26, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-27", controlId: 27, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" }
];

export const controlsData: Control[] = [
    {
        criadoEm: '2024-06-24',
        id: 1,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-01',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Plano de Inspeção e Limpeza das Estruturas',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementação Futura',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-05',
        frequenciaMeses: 6,
        proximaVerificacao: '2024-12-02',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-01 Inspeção Limpeza',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;RUBENS.ALENCAR@RUMOLOG.COM;CS264288@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '30',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 2,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-02',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'SPDA - Aterramento dos Silos, Armazéns e Equipamentos',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado com Pendência',
        donoControle: 'Pablo Lacerda Aguiar',
        emailDono: 'pablo.aguiar@rumolog.com',
        area: 'MANUTENÇÃO',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-02 SPDA',
        evidencia: 'E-LDT-RMO-02202-001-00 - LAUDO ATERRAMENTO E SPDA TRO',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '30',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 3,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-03',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Instalação elétrica adequada e classificação de área',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementação Futura',
        donoControle: 'Bruno Edison Silva Dalosto',
        emailDono: 'bruno.dalosto@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 6,
        proximaVerificacao: '2024-11-30',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-03  Área classificada',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;CS306132@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '30',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 4,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-04',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Dispositivo de Supressão de Pó',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Não Implementado',
        donoControle: 'Pablo Lacerda Aguiar',
        emailDono: 'pablo.aguiar@rumolog.com',
        area: 'MANUTENÇÃO',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-04 Supressão de Pó',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '30',
        criticidade: 'Sim',
    },
     {
        criadoEm: '2024-06-24',
        id: 5,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-05',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Controle de temperatura em equipamentos e ambientes',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado',
        donoControle: 'Pablo Lacerda Aguiar',
        emailDono: 'pablo.aguiar@rumolog.com',
        area: 'MANUTENÇÃO',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-10',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-05 Controle de Temp.',
        evidencia: 'Planilhas de medição',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '30',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 6,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-06',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Procedimento de trabalho a quente',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-01-20',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-01-15',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-06 Trab. Quente',
        evidencia: 'IT-CORP-SEG-000',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;edson.abe@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '30',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 7,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-07',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Treinamento de Brigada de Emergência',
        tipo: 'Mitigatório',
        classificacao: 'Pessoa',
        status: 'Implementado',
        donoControle: 'Bruno Edison Silva Dalosto',
        emailDono: 'bruno.dalosto@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-05-15',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-10',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-07 Brigada',
        evidencia: 'Lista de Presença',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '30',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 8,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-08',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Inspeção e manutenção de sistemas de combate a incêndio',
        tipo: 'Mitigatório',
        classificacao: 'Equipamento',
        status: 'Implementado com Pendência',
        donoControle: 'Bruno Edison Silva Dalosto',
        emailDono: 'bruno.dalosto@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-01',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-01',
        validacao: 'ATRASADO',
        onePager: '01-08 Insp. Incendio',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '30',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 9,
        codigoMUE: 'RUMO 02',
        titulo: 'RUMO 02-01',
        idRiscoMUE: 29,
        descricaoMUE: 'Colapso de estrutura (silo, armazém, torre de elevador, moega)',
        nomeControle: 'Inspeção predial em estruturas de concreto e metálicas',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Pablo Lacerda Aguiar',
        emailDono: 'pablo.aguiar@rumolog.com',
        area: 'MANUTENÇÃO',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '02-01 Insp Predial',
        evidencia: 'Laudos de Inspeção',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '29',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 10,
        codigoMUE: 'RUMO 02',
        titulo: 'RUMO 02-02',
        idRiscoMUE: 29,
        descricaoMUE: 'Colapso de estrutura (silo, armazém, torre de elevador, moega)',
        nomeControle: 'Monitoramento de Recalque e Verticalidade',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Não Implementado',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-05',
        frequenciaMeses: 6,
        proximaVerificacao: '2024-12-02',
        validacao: 'DENTRO DO PRAZO',
        onePager: '02-02 Monit Recalque',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '29',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 11,
        codigoMUE: 'RUMO 03',
        titulo: 'RUMO 03-01',
        idRiscoMUE: 2,
        descricaoMUE: 'Descarrilamento em AMV durante manobra de entrada/saída do terminal',
        nomeControle: 'Inspeção de AMVs',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado com Pendência',
        donoControle: 'Victor Dimitri Zolotareff',
        emailDono: 'victor.zolotareff@rumolog.com',
        area: 'VIA PERMANENTE',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-01',
        validacao: 'ATRASADO',
        onePager: '03-01 Insp AMV',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '2',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 12,
        codigoMUE: 'RUMO 03',
        titulo: 'RUMO 03-02',
        idRiscoMUE: 2,
        descricaoMUE: 'Descarrilamento em AMV durante manobra de entrada/saída do terminal',
        nomeControle: 'Manutenção de AMVs',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Não Implementado',
        donoControle: 'Victor Dimitri Zolotareff',
        emailDono: 'victor.zolotareff@rumolog.com',
        area: 'VIA PERMANENTE',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-01',
        validacao: 'ATRASADO',
        onePager: '03-02 Manut AMV',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '2',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 13,
        codigoMUE: 'RUMO 04',
        titulo: 'RUMO 04-01',
        idRiscoMUE: 1,
        descricaoMUE: 'Queda de pessoa ou objeto de passarela/plataforma/escada',
        nomeControle: 'Inspeção de Guarda Corpo',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado com Pendência',
        donoControle: 'Bruno Edison Silva Dalosto',
        emailDono: 'bruno.dalosto@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 3,
        proximaVerificacao: '2024-09-01',
        validacao: 'DENTRO DO PRAZO',
        onePager: '04-01 Insp Guarda Corpo',
        evidencia: 'Checklist de Inspeção',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: '1',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 14,
        codigoMUE: 'RUMO 05',
        titulo: 'RUMO 05-01',
        idRiscoMUE: 18,
        descricaoMUE: 'Contaminação de produto (soja/farelo/milho)',
        nomeControle: 'Controle de qualidade de produto',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado com Pendência',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-10',
        validacao: 'DENTRO DO PRAZO',
        onePager: '05-01 Qualidade',
        evidencia: 'Relatórios de Análise',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Comercial',
        topRiskAssociado: 'Risco 04.Perdas ou danos ao produto',
        idRiscos: '18',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 15,
        codigoMUE: 'RUMO 06',
        titulo: 'RUMO 06-01',
        idRiscoMUE: 14,
        descricaoMUE: 'Exposição a produto químico durante operação de fumigação/expurgo',
        nomeControle: 'Procedimento de Fumigação/Expurgo',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Pablo Lacerda Aguiar',
        emailDono: 'pablo.aguiar@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '06-01 Proc Fumigação',
        evidencia: 'IT-CORP-SEG-0XX',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: '14',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 16,
        codigoMUE: 'RUMO 07',
        titulo: 'RUMO 07-01',
        idRiscoMUE: 21,
        descricaoMUE: 'Vazamento de produtos perigosos em bacias de contenção',
        nomeControle: 'Inspeção e Manutenção de Bacias de Contenção',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado com Pendência',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-05',
        frequenciaMeses: 3,
        proximaVerificacao: '2024-09-03',
        validacao: 'DENTRO DO PRAZO',
        onePager: '07-01 Bacias Contenção',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Meio Ambiente',
        topRiskAssociado: 'Risco 03.Dano ambiental e/ou à comunidade',
        idRiscos: '21',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 17,
        codigoMUE: 'RUMO 08',
        titulo: 'RUMO 08-01',
        idRiscoMUE: 13,
        descricaoMUE: 'Atropelamento em cruzamento rodoferroviário',
        nomeControle: 'Manutenção da Sinalização Passiva em PN',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'VIA PERMANENTE',
        dataUltimaVerificacao: '2024-01-20',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-01-15',
        validacao: 'DENTRO DO PRAZO',
        onePager: '08-01 Manut Sinalização',
        evidencia: 'IT-CORP-SEG-000',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;edson.abe@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: '13',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 18,
        codigoMUE: 'RUMO 08',
        titulo: 'RUMO 08-02',
        idRiscoMUE: 13,
        descricaoMUE: 'Atropelamento em cruzamento rodoferroviário',
        nomeControle: 'Manutenção da Sinalização Ativa em PN',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado',
        donoControle: 'Bruno Edison Silva Dalosto',
        emailDono: 'bruno.dalosto@rumolog.com',
        area: 'VIA PERMANENTE',
        dataUltimaVerificacao: '2024-05-15',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-10',
        validacao: 'DENTRO DO PRAZO',
        onePager: '08-02 Manut Sinalização Ativa',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: '13',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 19,
        codigoMUE: 'RUMO 08',
        titulo: 'RUMO 08-03',
        idRiscoMUE: 13,
        descricaoMUE: 'Atropelamento em cruzamento rodoferroviário',
        nomeControle: 'Campanha de Conscientização em PN',
        tipo: 'Preventivo',
        classificacao: 'Pessoa',
        status: 'Implementado',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-01',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-28',
        validacao: 'DENTRO DO PRAZO',
        onePager: '08-03 Campanha PN',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: '13',
        criticidade: 'Não',
    },
    {
        criadoEm: '2024-06-24',
        id: 20,
        codigoMUE: 'RUMO 09',
        titulo: 'RUMO 09-01',
        idRiscoMUE: 27,
        descricaoMUE: 'Engolfamento em espaço confinado (silo, secador, poço de elevador)',
        nomeControle: 'Permissão de Entrada e Trabalho em Espaço Confinado (PET)',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Victor Dimitri Zolotareff',
        emailDono: 'victor.zolotareff@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '09-01 PET',
        evidencia: 'IT-CORP-SEG-00Y',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: '27',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 21,
        codigoMUE: 'RUMO 09',
        titulo: 'RUMO 09-02',
        idRiscoMUE: 27,
        descricaoMUE: 'Engolfamento em espaço confinado (silo, secador, poço de elevador)',
        nomeControle: 'Bloqueio de energias perigosas',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-05',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '09-02 Bloqueio',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: '27',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 22,
        codigoMUE: 'RUMO 09',
        titulo: 'RUMO 09-03',
        idRiscoMUE: 27,
        descricaoMUE: 'Engolfamento em espaço confinado (silo, secador, poço de elevador)',
        nomeControle: 'Treinamento de equipes de resgate e salvamento',
        tipo: 'Mitigatório',
        classificacao: 'Pessoa',
        status: 'Implementado',
        donoControle: 'Victor Dimitri Zolotareff',
        emailDono: 'victor.zolotareff@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-31',
        validacao: 'DENTRO DO PRAZO',
        onePager: '09-03 Treinamento',
        evidencia: 'IT-CORP-SEG-00Z',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: '27',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 23,
        codigoMUE: 'RUMO 10',
        titulo: 'RUMO 10-01',
        idRiscoMUE: 25,
        descricaoMUE: 'Assalto a carga em movimento ou parada',
        nomeControle: 'Monitoramento de Trens e Alertas de Parada',
        tipo: 'Preventivo',
        classificacao: 'Sistema',
        status: 'Implementado com Pendência',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-01',
        validacao: 'ATRASADO',
        onePager: '10-01 Monitoramento',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 04.Perdas ou danos ao produto',
        idRiscos: '25',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 24,
        codigoMUE: 'RUMO 10',
        titulo: 'RUMO 10-02',
        idRiscoMUE: 25,
        descricaoMUE: 'Assalto a carga em movimento ou parada',
        nomeControle: 'Escolta de trens em trechos críticos',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'SEGURANÇA PATRIMONIAL',
        dataUltimaVerificacao: '2024-01-20',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-01-15',
        validacao: 'DENTRO DO PRAZO',
        onePager: '10-02 Escolta',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;edson.abe@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 04.Perdas ou danos ao produto',
        idRiscos: '25',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 25,
        codigoMUE: 'RUMO 10',
        titulo: 'RUMO 10-03',
        idRiscoMUE: 25,
        descricaoMUE: 'Assalto a carga em movimento ou parada',
        nomeControle: 'Comunicação com autoridades policiais',
        tipo: 'Mitigatório',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'SEGURANÇA PATRIMONIAL',
        dataUltimaVerificacao: '2024-05-15',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-10',
        validacao: 'DENTRO DO PRAZO',
        onePager: '10-03 Comunicação',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 04.Perdas ou danos ao produto',
        idRiscos: '25',
        criticidade: 'Não',
    },
    {
        criadoEm: '2024-06-24',
        id: 26,
        codigoMUE: 'RUMO 11',
        titulo: 'RUMO 11-01',
        idRiscoMUE: 28,
        descricaoMUE: 'Danos a equipamentos por descarga atmosférica',
        nomeControle: 'SPDA - Sistema de Proteção contra Descargas Atmosféricas',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado com Pendência',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'MANUTENÇÃO',
        dataUltimaVerificacao: '2024-06-01',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-28',
        validacao: 'DENTRO DO PRAZO',
        onePager: '11-01 SPDA',
        evidencia: 'Laudo de SPDA',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: '28',
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 27,
        codigoMUE: 'RUMO 12',
        titulo: 'RUMO 12-01',
        idRiscoMUE: 22,
        descricaoMUE: 'Invasão à área operacional por pessoas não autorizadas',
        nomeControle: 'Controle de Acesso de Pessoas e Veículos',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'SEGURANÇA PATRIMONIAL',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '12-01 Controle Acesso',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;edson.abe@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: '22',
        criticidade: 'Sim',
    },
];

const newRisksFromIdentification: Risk[] = identifiedRisksData.map(ir => {
    const imp = ir.corporateImpact;
    const org = ir.organizationalRelevance;
    const prob = ir.contextualizedProbability;
    const ctrl = ir.currentControlCapacity;
    const tempo = ir.containmentTime;
    const facil = ir.technicalFeasibility;
    const ier = Math.round(((imp * 0.3) + (org * 0.1) + (prob * 0.2) + (ctrl * 0.15) + (tempo * 0.15) + (facil * 0.1)) * 100);

    let tipoIER: Risk['tipoIER'];
    if (ier >= 800) tipoIER = 'Crítico';
    else if (ier >= 700) tipoIER = 'Prioritário';
    else if (ier >= 600) tipoIER = 'Gerenciável';
    else tipoIER = 'Aceitável';

    return {
        id: ir.id,
        risco: ir.riskName,
        topRiskAssociado: ir.topRisk,
        fatorDeRisco: ir.riskFactor,
        imp: ir.corporateImpact,
        org: ir.organizationalRelevance,
        prob: ir.contextualizedProbability,
        ctrl: ir.currentControlCapacity,
        tempo: ir.containmentTime,
        facil: ir.technicalFeasibility,
        criado: new Date().toISOString().split('T')[0],
        criadoPor: 'Sistema de Identificação',
        status: 'Novo',
        taxonomia: '',
        gerencia: '',
        categoria: '',
        ier: ier,
        tipoIER: tipoIER,
        responsavelBowtie: '',
        x: 0,
        y: 0,
        origem: 'Identificação de Risco',
        modificado: '',
        modificadoPor: '',
        bowtieRealizado: 'Não Realizado',
        urlDoCC: '',
        possuiCC: 'Não',
        pilar: '',
        temaMaterial: '',
        pilarESG: '',
        englobador: '',
        horizonteTempo: '',
        geOrigemRisco: '',
        observacao: ir.currentControls,
        dataAlteracaoCuradoria: '',
        contexto: ir.riskScenario,
    }
});

const defaultEscalationRule: EscalationRule = {
  metricType: 'days',
  levels: [
    { level: 0, triggerDays: 0, triggerPercentage: 0, role: 'Gerente do Dono do Controle', responsible: 'Nome Gerente', enabled: true },
    { level: 1, triggerDays: 5, triggerPercentage: 10, role: 'Gerente Executivo', responsible: 'Nome Gerente Exec.', enabled: true },
    { level: 2, triggerDays: 10, triggerPercentage: 20, role: 'Diretor', responsible: 'Nome Diretor', enabled: true },
    { level: 3, triggerDays: 15, triggerPercentage: 30, role: 'VP', responsible: 'Nome VP', enabled: true },
  ],
};


const existingRisks: Risk[] = [
  { id: '1', status: 'Em Análise', gerencia: 'Operação', risco: 'Queda de pessoa ou objeto de passarela/plataforma/escada', topRiskAssociado: 'Quedas de Risco OLN Operacional', fatorDeRisco: 'Material Rodante', imp: 8, org: 0, prob: 7, ctrl: 7, tempo: 10, facil: 8, ier: 815, contexto: '70%', bowtieRealizado: 'Não Realizado', observacao: '', pilar: 'G - Governança', pilarESG: 'S - Social', temaMaterial: 'Integridade de Ativos', geOrigemRisco: 'Controles Internos', origem: 'GR - Observação', taxonomia: 'RISK-CR-Negócio-1', englobador: 'Curto Prazo', horizonteTempo: 'Curto Prazo', tipoIER: 'Crítico', urlDoCC: '', possuiCC: 'Não', modificado: '2025-07-15', criado: '2025-07-15', criadoPor: 'Admin', modificadoPor: 'Admin', categoria: 'RISK-CR-Negócio', responsavelBowtie: 'Guilherme', x: 9, y: 9.5, dataAlteracaoCuradoria: '2025-07-15', escalationRule: defaultEscalationRule},
  { id: '2', status: 'Em Análise', gerencia: 'Tecnologia', risco: 'Descarrilamento em AMV durante manobra de entrada/saída do terminal', topRiskAssociado: 'Comprometimento de Risco 07. I. Tecnológico', fatorDeRisco: 'Tecnologia e Segurança da Informação', imp: 9, org: 0, prob: 8, ctrl: 8, tempo: 6, facil: 8, ier: 805, contexto: '40%', bowtieRealizado: 'Não Realizado', observacao: '', pilar: 'E - Ambiental', pilarESG: 'S - Social', temaMaterial: 'Integridade Tecnológica', geOrigemRisco: 'Controles Internos', origem: 'GR - Observação', taxonomia: 'RISK-TC-Negócio-2', englobador: 'Longo Prazo', horizonteTempo: 'Longo Prazo', tipoIER: 'Crítico', urlDoCC: '', possuiCC: 'Não', modificado: '2025-07-15', criado: '2025-07-15', criadoPor: 'Admin', modificadoPor: 'Admin', categoria: 'RISK-TC-Negócio', responsavelBowtie: 'Silvio Hesi', x: 9.5, y: 8, dataAlteracaoCuradoria: '2025-07-15', escalationRule: defaultEscalationRule},
  { id: '29', status: 'Em Análise', gerencia: 'Operação', risco: 'Colapso de estrutura (silo, armazém, torre de elevador, moega)', topRiskAssociado: 'Colapso de Risco OLN Operacional', fatorDeRisco: 'Terminais', imp: 6, org: 0, prob: 4, ctrl: 8, tempo: 8, facil: 4, ier: 660, contexto: '', bowtieRealizado: 'Realizado', observacao: '', pilar: 'G - Governança', pilarESG: 'S - Social', temaMaterial: 'Integridade de Ativos', geOrigemRisco: 'Controles Internos', origem: 'GR - Observação', taxonomia: 'RISK-OPE-Negócio-29', englobador: 'Longo Prazo', horizonteTempo: 'Longo Prazo', tipoIER: 'Gerenciável', urlDoCC: 'https://rumo.com/bowtie/29', possuiCC: 'Sim', modificado: '2025-07-15', criado: '2025-07-15', criadoPor: 'Admin', modificadoPor: 'Admin', categoria: 'RISK-OPE-Negócio', responsavelBowtie: 'Guilherme', x: 4, y: 7, dataAlteracaoCuradoria: '2025-07-15', escalationRule: defaultEscalationRule},
  { id: '30', status: 'Em Análise', gerencia: 'Operação', risco: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)', topRiskAssociado: 'Incêndio e Risco OLN Operacional', fatorDeRisco: 'Segurança do Trabalho', imp: 4, org: 0, prob: 4, ctrl: 4, tempo: 8, facil: 4, ier: 660, contexto: '', bowtieRealizado: 'Realizado', observacao: '', pilar: 'G - Governança', pilarESG: 'S - Social', temaMaterial: 'Integridade de Ativos', geOrigemRisco: 'Controles Internos', origem: 'GR - Observação', taxonomia: 'RISK-OPE-Negócio-30', englobador: 'Longo Prazo', horizonteTempo: 'Longo Prazo', tipoIER: 'Gerenciável', urlDoCC: 'https://rumo.com/bowtie/30', possuiCC: 'Sim', modificado: '2025-07-15', criado: '2025-07-15', criadoPor: 'Admin', modificadoPor: 'Admin', categoria: 'RISK-OPE-Negócio', responsavelBowtie: 'Guilherme', x: 4, y: 7, dataAlteracaoCuradoria: '2025-07-15', escalationRule: defaultEscalationRule },
];


export const risksData: Risk[] = [...existingRisks, ...newRisksFromIdentification.map(r => ({ ...r, escalationRule: defaultEscalationRule }))];


export const complianceChartData = [
  { month: 'Jan', compliance: 88, target: 90 },
  { month: 'Feb', compliance: 91, target: 90 },
  { month: 'Mar', compliance: 92, target: 90 },
  { month: 'Apr', compliance: 89, target: 90 },
  { month: 'May', compliance: 93, target: 90 },
  { month: 'Jun', compliance: 95, target: 90 },
  { month: 'Jul', compliance: 85.7, target: 90 },
];

export const initialBowtieData: BowtieData[] = [
    {
        id: 'B001',
        riskId: '29',
        createdAt: '2024-07-20',
        responsible: 'Admin Rumo',
        approvalStatus: 'Aprovado',
        version: 2,
        topEvent: {
            title: "Colapso de estrutura",
            description: "Armazenagem"
        },
        threats: [
            { 
                id: 'T1', 
                title: 'Sobrecarga da estrutura',
                barriers: [
                    { id: 'B1-1', title: 'Controle de Peso', responsible: 'Operação', effectiveness: 'Eficaz', status: 'Implementado' },
                ]
            },
        ],
        consequences: [
            {
                id: 'C1',
                title: 'Perda de material',
                barriers: [
                    { id: 'B3-1', title: 'Seguro Patrimonial', responsible: 'Financeiro', effectiveness: 'Eficaz', status: 'Implementado' },
                ]
            },
        ]
    }
];

export const getEmptyBowtie = (risk: Risk): BowtieData => {
    const newId = `B${Math.random().toString(36).substr(2, 9)}`;
    const newThreat: BowtieThreat = {
        id: 'T1',
        title: 'Nova Ameaça',
        barriers: [{
            id: 'B1-1',
            title: 'Nova Barreira Preventiva',
            responsible: 'Indefinido',
            effectiveness: 'Eficaz',
            status: 'Pendente'
        }]
    };
     const newConsequence: BowtieConsequence = {
        id: 'C1',
        title: 'Nova Consequência',
        barriers: [{
            id: 'B2-1',
            title: 'Nova Barreira Mitigatória',
            responsible: 'Indefinido',
            effectiveness: 'Eficaz',
            status: 'Pendente'
        }]
    };

    return {
        id: newId,
        riskId: risk.id,
        createdAt: new Date().toISOString().split('T')[0],
        responsible: risk.responsavelBowtie || 'Não definido',
        approvalStatus: 'Em aprovação',
        version: 1,
        topEvent: {
            title: risk.risco,
            description: risk.gerencia,
        },
        threats: [newThreat],
        consequences: [newConsequence],
    };
};
