
import type { Risk, RecentActivity, BowtieData } from './types';

export const kpiData = {
  compliance: {
    value: 92.5,
    change: 1.2,
  },
  overdueItems: {
    value: 8,
    change: -3,
  },
  criticalRisks: {
    value: 3,
    change: 1,
  },
  controlDeviations: {
    value: 5,
    change: 2,
  },
};

export const complianceChartData = [
  { month: 'Jan', compliance: 88, target: 90 },
  { month: 'Feb', compliance: 91, target: 90 },
  { month: 'Mar', compliance: 92, target: 90 },
  { month: 'Apr', compliance: 89, target: 90 },
  { month: 'May', compliance: 93, target: 90 },
  { month: 'Jun', compliance: 95, target: 90 },
  { month: 'Jul', compliance: 92.5, target: 90 },
];

export const recentActivityData: RecentActivity[] = [
    {
        id: '1',
        user: { name: 'Alice Johnson', avatarUrl: 'https://picsum.photos/seed/101/32/32' },
        action: 'criou um novo risco',
        target: 'Falha no sistema de freios',
        timestamp: '2 horas atrás',
    },
    {
        id: '2',
        user: { name: 'Bob Williams', avatarUrl: 'https://picsum.photos/seed/102/32/32' },
        action: 'atualizou o controle',
        target: 'Inspeção de via semanal',
        timestamp: '5 horas atrás',
    },
    {
        id: '3',
        user: { name: 'Carla Davis', avatarUrl: 'https://picsum.photos/seed/103/32/32' },
        action: 'aprovou o risco',
        target: 'Descarrilamento em pátio',
        timestamp: '1 dia atrás',
    },
    {
        id: '4',
        user: { name: 'David Miller', avatarUrl: 'https://picsum.photos/seed/104/32/32' },
        action: 'comentou no KPI',
        target: '% de conformidade de inspeção',
        timestamp: '2 dias atrás',
    },
];

export const risksData: Risk[] = [
  {
    id: 'R001',
    gerencia: 'Operação',
    risco: 'Descarrilamento em Curva',
    descricaoDoRisco: 'Risco de descarrilamento de vagões em curvas de raio reduzido na Malha Sul, especialmente em trechos com histórico de desgaste de trilhos.',
    dataDeIdentificacao: '2023-01-15',
    origemDoRisco: 'Interna',
    causaRaizDoRisco: 'Desgaste excessivo do boleto do trilho combinado com velocidade inadequada do trem.',
    consequenciaDoRisco: 'Danos ao material rodante, à via e à carga, interrupção do tráfego ferroviário e potenciais impactos ambientais.',
    tipoDeRisco: 'Operacional',
    processoAfetado: 'Operação Ferroviária',
    probabilidadeInerente: 'Possível',
    impactoInerente: 'Catastrófico',
    nivelDeRiscoInerente: 'Crítico',
    estrategia: 'Mitigar',
    descricaoDoControle: 'Inspeção ultrassônica de trilhos para detecção de defeitos e controle de velocidade via ATC (Automatic Train Control).',
    naturezaDoControle: 'Semi-Sistêmico',
    tipoDeControle: 'Preventivo',
    classificacaoDoControle: 'Chave',
    frequencia: 'Semanal',
    eficaciaDoControle: 'Eficaz',
    probabilidadeResidual: 'Raro',
    impactoResidual: 'Maior',
    nivelDeRiscoResidual: 'Alto',
    statusDoRisco: 'Em Tratamento',
    responsavelPeloRisco: 'João da Silva',
    dataDaUltimaRevisao: '2024-07-10',
    dataDaProximaRevisao: '2024-10-10',
  },
  {
    id: 'R002',
    gerencia: 'Suprimentos',
    risco: 'Atraso na Entrega de Peças Críticas',
    descricaoDoRisco: 'Atraso na entrega de componentes essenciais (ex: sapatas de freio, rodeiros) por parte de fornecedores, impactando a disponibilidade da frota.',
    dataDeIdentificacao: '2023-02-20',
    origemDoRisco: 'Externa',
    causaRaizDoRisco: 'Problemas logísticos do fornecedor e falta de fornecedores alternativos homologados.',
    consequenciaDoRisco: 'Redução da disponibilidade de locomotivas e vagões, impactando o plano de transporte.',
    tipoDeRisco: 'Operacional',
    processoAfetado: 'Manutenção de Material Rodante',
    probabilidadeInerente: 'Provável',
    impactoInerente: 'Moderado',
    nivelDeRiscoInerente: 'Alto',
    estrategia: 'Mitigar',
    descricaoDoControle: 'Manutenção de estoque de segurança para itens críticos e desenvolvimento de fornecedores alternativos.',
    naturezaDoControle: 'Manual',
    tipoDeControle: 'Corretivo',
    classificacaoDoControle: 'Não Chave',
    frequencia: 'Mensal',
    eficaciaDoControle: 'Pouco Eficaz',
    probabilidadeResidual: 'Possível',
    impactoResidual: 'Moderado',
    nivelDeRiscoResidual: 'Médio',
    statusDoRisco: 'Aberto',
    responsavelPeloRisco: 'Maria Oliveira',
    dataDaUltimaRevisao: '2024-06-25',
    dataDaProximaRevisao: '2024-09-25',
  },
  {
    id: 'R003',
    gerencia: 'Regulatório',
    risco: 'Alteração em Norma da ANTT',
    descricaoDoRisco: 'Publicação de nova resolução pela Agência Nacional de Transportes Terrestres (ANTT) com requisitos mais rígidos para a sinalização ferroviária.',
    dataDeIdentificacao: '2023-03-10',
    origemDoRisco: 'Externa',
    causaRaizDoRisco: 'Evolução do marco regulatório do setor ferroviário.',
    consequenciaDoRisco: 'Necessidade de investimentos não planejados para adequação da infraestrutura e risco de multas por não conformidade.',
    tipoDeRisco: 'Regulatório',
    processoAfetado: 'Conformidade Regulatória',
    probabilidadeInerente: 'Possível',
    impactoInerente: 'Maior',
    nivelDeRiscoInerente: 'Alto',
    estrategia: 'Aceitar',
    descricaoDoControle: 'Monitoramento contínuo de novas publicações e participação em consultas públicas da ANTT. Criação de um plano de adequação.',
    naturezaDoControle: 'Manual',
    tipoDeControle: 'Detectivo',
    classificacaoDoControle: 'Chave',
    frequencia: 'Diário',
    eficaciaDoControle: 'Eficaz',
    probabilidadeResidual: 'Improvável',
    impactoResidual: 'Maior',
    nivelDeRiscoResidual: 'Médio',
    statusDoRisco: 'Em Tratamento',
    responsavelPeloRisco: 'Carlos Pereira',
    dataDaUltimaRevisao: '2024-07-15',
    dataDaProximaRevisao: '2024-08-15',
  },
  {
    id: 'R004',
    gerencia: 'Ambiental',
    risco: 'Vazamento de Carga Perigosa',
    descricaoDoRisco: 'Vazamento de produto químico (ex: óleo diesel, soda cáustica) durante o transporte, com potencial de contaminação do solo e de corpos hídricos.',
    dataDeIdentificacao: '2023-04-05',
    origemDoRisco: 'Interna',
    causaRaizDoRisco: 'Avaria no tanque do vagão causada por colisão ou fadiga de material.',
    consequenciaDoRisco: 'Dano ambiental significativo, multas dos órgãos ambientais, dano à imagem da companhia e custos de remediação.',
    tipoDeRisco: 'Ambiental',
    processoAfetado: 'Transporte de Cargas',
    probabilidadeInerente: 'Improvável',
    impactoInerente: 'Catastrófico',
    nivelDeRiscoInerente: 'Crítico',
    estrategia: 'Mitigar',
    descricaoDoControle: 'Uso de vagões-tanque com certificação e inspeção rigorosa. Plano de Atendimento a Emergências (PAE) com equipes e recursos dedicados.',
    naturezaDoControle: 'Sistêmico',
    tipoDeControle: 'Preventivo',
    classificacaoDoControle: 'Chave',
    frequencia: 'Anual',
    eficaciaDoControle: 'Muito Eficaz',
    probabilidadeResidual: 'Raro',
    impactoResidual: 'Maior',
    nivelDeRiscoResidual: 'Alto',
    statusDoRisco: 'Mitigado',
    responsavelPeloRisco: 'Ana Souza',
    dataDaUltimaRevisao: '2024-05-20',
    dataDaProximaRevisao: '2025-05-20',
  },
  {
    id: 'R005',
    gerencia: 'Tecnologia',
    risco: 'Ataque Cibernético ao CCO',
    descricaoDoRisco: 'Invasão e comprometimento dos sistemas do Centro de Controle Operacional (CCO), afetando a capacidade de controlar a circulação dos trens.',
    dataDeIdentificacao: '2023-05-12',
    origemDoRisco: 'Externa',
    causaRaizDoRisco: 'Exploração de vulnerabilidade de software ou phishing direcionado a funcionários do CCO.',
    consequenciaDoRisco: 'Paralisação total ou parcial da malha ferroviária, risco à segurança operacional e perda de dados confidenciais.',
    tipoDeRisco: 'Estratégico',
    processoAfetado: 'Controle de Tráfego',
    probabilidadeInerente: 'Improvável',
    impactoInerente: 'Catastrófico',
    nivelDeRiscoInerente: 'Crítico',
    estrategia: 'Mitigar',
    descricaoDoControle: 'Firewall de nova geração, sistema de detecção de intrusão (IDS/IPS), segregação de redes e programa de conscientização de segurança.',
    naturezaDoControle: 'Sistêmico',
    tipoDeControle: 'Preventivo',
    classificacaoDoControle: 'Chave',
    frequencia: 'Diário',
    eficaciaDoControle: 'Eficaz',
    probabilidadeResidual: 'Raro',
    impactoResidual: 'Catastrófico',
    nivelDeRiscoResidual: 'Crítico',
    statusDoRisco: 'Aberto',
    responsavelPeloRisco: 'Pedro Martins',
    dataDaUltimaRevisao: '2024-07-01',
    dataDaProximaRevisao: '2024-10-01',
  },
  {
    id: 'R006',
    gerencia: 'Financeiro',
    risco: 'Variação Cambial em Contratos',
    descricaoDoRisco: 'Exposição a flutuações cambiais em contratos de fornecimento de equipamentos e peças importadas.',
    dataDeIdentificacao: '2023-06-01',
    origemDoRisco: 'Externa',
    causaRaizDoRisco: 'Volatilidade do mercado de câmbio.',
    consequenciaDoRisco: 'Aumento inesperado dos custos de aquisição e impacto no orçamento de investimentos (CAPEX).',
    tipoDeRisco: 'Financeiro',
    processoAfetado: 'Gestão Financeira',
    probabilidadeInerente: 'Provável',
    impactoInerente: 'Maior',
    nivelDeRiscoInerente: 'Alto',
    estrategia: 'Transferir',
    descricaoDoControle: 'Utilização de instrumentos de hedge cambial (Ex: NDF, Opções) para travar a taxa de câmbio em contratos relevantes.',
    naturezaDoControle: 'Sistêmico',
    tipoDeControle: 'Preventivo',
    classificacaoDoControle: 'Chave',
    frequencia: 'Trimestral',
    eficaciaDoControle: 'Muito Eficaz',
    probabilidadeResidual: 'Possível',
    impactoResidual: 'Menor',
    nivelDeRiscoResidual: 'Baixo',
    statusDoRisco: 'Mitigado',
    responsavelPeloRisco: 'Fernanda Lima',
    dataDaUltimaRevisao: '2024-06-30',
    dataDaProximaRevisao: '2024-09-30',
  },
  {
    id: 'R007',
    gerencia: 'RH',
    risco: 'Perda de Profissionais Chave',
    descricaoDoRisco: 'Saída de profissionais com conhecimento técnico especializado e difícil de repor (ex: especialistas em sinalização, maquinistas instrutores).',
    dataDeIdentificacao: '2023-07-22',
    origemDoRisco: 'Interna',
    causaRaizDoRisco: 'Falta de um plano de sucessão estruturado e concorrência do mercado.',
    consequenciaDoRisco: 'Perda de conhecimento crítico, descontinuidade de projetos e sobrecarga das equipes remanescentes.',
    tipoDeRisco: 'Estratégico',
    processoAfetado: 'Gestão de Talentos',
    probabilidadeInerente: 'Possível',
    impactoInerente: 'Moderado',
    nivelDeRiscoInerente: 'Médio',
    estrategia: 'Mitigar',
    descricaoDoControle: 'Implementação de programa de mentoria, mapeamento de sucessão e política de retenção de talentos.',
    naturezaDoControle: 'Manual',
    tipoDeControle: 'Preventivo',
    classificacaoDoControle: 'Não Chave',
    frequencia: 'Anual',
    eficaciaDoControle: 'Pouco Eficaz',
    probabilidadeResidual: 'Possível',
    impactoResidual: 'Moderado',
    nivelDeRiscoResidual: 'Médio',
    statusDoRisco: 'Aberto',
    responsavelPeloRisco: 'Ricardo Andrade',
    dataDaUltimaRevisao: '2024-07-20',
    dataDaProximaRevisao: '2025-01-20',
  },
  {
    id: 'R008',
    gerencia: 'Jurídico',
    risco: 'Ações Trabalhistas',
    descricaoDoRisco: 'Aumento do volume de reclamações trabalhistas relacionadas a horas extras e periculosidade.',
    dataDeIdentificacao: '2023-08-15',
    origemDoRisco: 'Interna',
    causaRaizDoRisco: 'Interpretações divergentes da legislação e falhas no registro de ponto.',
    consequenciaDoRisco: 'Aumento do passivo trabalhista, custos com advogados e impacto na imagem de empregador.',
    tipoDeRisco: 'Legal',
    processoAfetado: 'Relações Trabalhistas',
    probabilidadeInerente: 'Provável',
    impactoInerente: 'Menor',
    nivelDeRiscoInerente: 'Médio',
    estrategia: 'Mitigar',
    descricaoDoControle: 'Revisão dos procedimentos de registro de jornada e treinamento das lideranças sobre a legislação.',
    naturezaDoControle: 'Manual',
    tipoDeControle: 'Corretivo',
    classificacaoDoControle: 'Não Chave',
    frequencia: 'Semestral',
    eficaciaDoControle: 'Eficaz',
    probabilidadeResidual: 'Possível',
    impactoResidual: 'Menor',
    nivelDeRiscoResidual: 'Baixo',
    statusDoRisco: 'Em Tratamento',
    responsavelPeloRisco: 'Beatriz Costa',
    dataDaUltimaRevisao: '2024-06-10',
    dataDaProximaRevisao: '2024-12-10',
  },
  {
    id: 'R009',
    gerencia: 'Comercial',
    risco: 'Perda de Cliente Estratégico',
    descricaoDoRisco: 'Risco de não renovação de contrato com um cliente que representa mais de 15% do faturamento de um corredor logístico.',
    dataDeIdentificacao: '2023-09-01',
    origemDoRisco: 'Externa',
    causaRaizDoRisco: 'Aumento da concorrência com o modal rodoviário e insatisfação com a qualidade do serviço.',
    consequenciaDoRisco: 'Queda abrupta na receita, ociosidade de ativos e impacto no resultado financeiro.',
    tipoDeRisco: 'Estratégico',
    processoAfetado: 'Gestão de Clientes',
    probabilidadeInerente: 'Possível',
    impactoInerente: 'Maior',
    nivelDeRiscoInerente: 'Alto',
    estrategia: 'Mitigar',
    descricaoDoControle: 'Plano de relacionamento com o cliente, renegociação de tarifas e apresentação de novos projetos de eficiência.',
    naturezaDoControle: 'Manual',
    tipoDeControle: 'Preventivo',
    classificacaoDoControle: 'Chave',
    frequencia: 'Mensal',
    eficaciaDoControle: 'Eficaz',
    probabilidadeResidual: 'Improvável',
    impactoResidual: 'Maior',
    nivelDeRiscoResidual: 'Médio',
    statusDoRisco: 'Mitigado',
    responsavelPeloRisco: 'Lucas Ferreira',
    dataDaUltimaRevisao: '2024-07-25',
    dataDaProximaRevisao: '2024-08-25',
  },
  {
    id: 'R010',
    gerencia: 'SMS',
    risco: 'Acidente com Passagem em Nível',
    descricaoDoRisco: 'Colisão de trem com veículo rodoviário em passagem em nível (PN) não sinalizada ou com falha de sinalização.',
    dataDeIdentificacao: '2023-10-11',
    origemDoRisco: 'Interna',
    causaRaizDoRisco: 'Imprudência de motoristas e falta de cancelas em PNs de alto fluxo.',
    consequenciaDoRisco: 'Vítimas fatais, danos materiais, interrupção da via e forte impacto negativo na imagem da empresa.',
    tipoDeRisco: 'Operacional',
    processoAfetado: 'Segurança Operacional',
    probabilidadeInerente: 'Possível',
    impactoInerente: 'Catastrófico',
    nivelDeRiscoInerente: 'Crítico',
    estrategia: 'Mitigar',
    descricaoDoControle: 'Campanhas de conscientização para motoristas e instalação de novas PNs com cancela e sinalização ativa.',
    naturezaDoControle: 'Semi-Sistêmico',
    tipoDeControle: 'Preventivo',
    classificacaoDoControle: 'Chave',
    frequencia: 'Anual',
    eficaciaDoControle: 'Eficaz',
    probabilidadeResidual: 'Improvável',
    impactoResidual: 'Catastrófico',
    nivelDeRiscoResidual: 'Crítico',
    statusDoRisco: 'Em Tratamento',
    responsavelPeloRisco: 'Sofia Ribeiro',
    dataDaUltimaRevisao: '2024-04-15',
    dataDaProximaRevisao: '2024-10-15',
  },
  {
    id: 'R011',
    gerencia: 'Expansão',
    risco: 'Atraso na Obtenção de Licença Ambiental',
    descricaoDoRisco: 'Demora na emissão da Licença de Instalação (LI) para um novo trecho ferroviário, atrasando o início das obras.',
    dataDeIdentificacao: '2023-11-05',
    origemDoRisco: 'Externa',
    causaRaizDoRisco: 'Burocracia do órgão ambiental e questionamentos de comunidades locais.',
    consequenciaDoRisco: 'Atraso no cronograma do projeto, aumento dos custos e postergação da geração de receita.',
    tipoDeRisco: 'Estratégico',
    processoAfetado: 'Projetos de Expansão',
    probabilidadeInerente: 'Provável',
    impactoInerente: 'Maior',
    nivelDeRiscoInerente: 'Alto',
    estrategia: 'Mitigar',
    descricaoDoControle: 'Contratação de consultoria especializada e engajamento proativo com o órgão ambiental e as comunidades.',
    naturezaDoControle: 'Manual',
    tipoDeControle: 'Preventivo',
    classificacaoDoControle: 'Chave',
    frequencia: 'Semanal',
    eficaciaDoControle: 'Eficaz',
    probabilidadeResidual: 'Possível',
    impactoResidual: 'Maior',
    nivelDeRiscoResidual: 'Alto',
    statusDoRisco: 'Aberto',
    responsavelPeloRisco: 'Daniel Almeida',
    dataDaUltimaRevisao: '2024-07-22',
    dataDaProximaRevisao: '2024-08-22',
  },
  {
    id: 'R012',
    gerencia: 'Operação',
    risco: 'Furto de Cabos de Sinalização',
    descricaoDoRisco: 'Furto recorrente de cabos de cobre do sistema de sinalização, causando falhas nos sinais e interrupção do tráfego.',
    dataDeIdentificacao: '2023-12-01',
    origemDoRisco: 'Externa',
    causaRaizDoRisco: 'Ação de criminosos e vulnerabilidade da infraestrutura em trechos isolados.',
    consequenciaDoRisco: 'Atrasos na operação, risco de acidentes e custos elevados de reposição e manutenção.',
    tipoDeRisco: 'Operacional',
    processoAfetado: 'Manutenção de Via Permanente',
    probabilidadeInerente: 'Quase Certo',
    impactoInerente: 'Moderado',
    nivelDeRiscoInerente: 'Alto',
    estrategia: 'Mitigar',
    descricaoDoControle: 'Vigilância motorizada nos trechos mais críticos e substituição de cabos de cobre por fibra óptica ou alumínio.',
    naturezaDoControle: 'Semi-Sistêmico',
    tipoDeControle: 'Corretivo',
    classificacaoDoControle: 'Não Chave',
    frequencia: 'Diário',
    eficaciaDoControle: 'Pouco Eficaz',
    probabilidadeResidual: 'Provável',
    impactoResidual: 'Moderado',
    nivelDeRiscoResidual: 'Alto',
    statusDoRisco: 'Aberto',
    responsavelPeloRisco: 'Juliana Santos',
    dataDaUltimaRevisao: '2024-07-18',
    dataDaProximaRevisao: '2024-08-18',
  },
  {
    id: 'R013',
    gerencia: 'Compliance',
    risco: 'Violação da Lei Anticorrupção',
    descricaoDoRisco: 'Envolvimento, direto ou indireto, em atos de corrupção em negociações com o poder público para obtenção de licenças ou contratos.',
    dataDeIdentificacao: '2024-01-20',
    origemDoRisco: 'Interna',
    causaRaizDoRisco: 'Falha nos controles de compliance e pressão por resultados.',
    consequenciaDoRisco: 'Pesadas multas, sanções legais, danos irreparáveis à reputação da empresa e prisão de executivos.',
    tipoDeRisco: 'Legal',
    processoAfetado: 'Relações Institucionais',
    probabilidadeInerente: 'Raro',
    impactoInerente: 'Catastrófico',
    nivelDeRiscoInerente: 'Alto',
    estrategia: 'Evitar',
    descricaoDoControle: 'Programa de compliance robusto, com treinamentos obrigatórios, canal de denúncias independente e due diligence de terceiros.',
    naturezaDoControle: 'Manual',
    tipoDeControle: 'Preventivo',
    classificacaoDoControle: 'Chave',
    frequencia: 'Anual',
    eficaciaDoControle: 'Muito Eficaz',
    probabilidadeResidual: 'Raro',
    impactoResidual: 'Menor',
    nivelDeRiscoResidual: 'Baixo',
    statusDoRisco: 'Fechado',
    responsavelPeloRisco: 'Marcos Mendes',
    dataDaUltimaRevisao: '2024-01-20',
    dataDaProximaRevisao: '2025-01-20',
  },
  {
    id: 'R014',
    gerencia: 'Tecnologia',
    risco: 'Indisponibilidade de Sistema Crítico',
    descricaoDoRisco: 'Falha no sistema de gestão de transporte (TMS), impedindo o planejamento e a execução das viagens.',
    dataDeIdentificacao: '2024-02-15',
    origemDoRisco: 'Interna',
    causaRaizDoRisco: 'Falha de hardware no data center ou bug de software após atualização.',
    consequenciaDoRisco: 'Incapacidade de gerar planos de transporte, resultando em atrasos e ineficiência operacional.',
    tipoDeRisco: 'Operacional',
    processoAfetado: 'Planejamento de Transporte',
    probabilidadeInerente: 'Improvável',
    impactoInerente: 'Maior',
    nivelDeRiscoInerente: 'Médio',
    estrategia: 'Mitigar',
    descricaoDoControle: 'Ambiente de data center redundante e plano de recuperação de desastres (DRP) testado periodicamente.',
    naturezaDoControle: 'Sistêmico',
    tipoDeControle: 'Corretivo',
    classificacaoDoControle: 'Chave',
    frequencia: 'Semestral',
    eficaciaDoControle: 'Eficaz',
    probabilidadeResidual: 'Raro',
    impactoResidual: 'Moderado',
    nivelDeRiscoResidual: 'Baixo',
    statusDoRisco: 'Mitigado',
    responsavelPeloRisco: 'Vanessa Rocha',
    dataDaUltimaRevisao: '2024-03-10',
    dataDaProximaRevisao: '2024-09-10',
  },
  {
    id: 'R015',
    gerencia: 'Comercial',
    risco: 'Imagem Prejudicada por Mídia Social',
    descricaoDoRisco: 'Viralização de conteúdo negativo nas redes sociais (ex: vídeo de acidente, reclamação de cliente) com grande repercussão.',
    dataDeIdentificacao: '2024-03-05',
    origemDoRisco: 'Externa',
    causaRaizDoRisco: 'Insatisfação do cliente ou incidente operacional tornado público.',
    consequenciaDoRisco: 'Dano à imagem e reputação da marca, com potencial impacto nas relações com investidores e clientes.',
    tipoDeRisco: 'Imagem',
    processoAfetado: 'Comunicação Corporativa',
    probabilidadeInerente: 'Possível',
    impactoInerente: 'Moderado',
    nivelDeRiscoInerente: 'Médio',
    estrategia: 'Aceitar',
    descricaoDoControle: 'Monitoramento de mídias sociais e plano de gerenciamento de crises de imagem, com porta-vozes definidos e Q&A preparado.',
    naturezaDoControle: 'Manual',
    tipoDeControle: 'Detectivo',
    classificacaoDoControle: 'Não Chave',
    frequencia: 'Diário',
    eficaciaDoControle: 'Eficaz',
    probabilidadeResidual: 'Possível',
    impactoResidual: 'Menor',
    nivelDeRiscoResidual: 'Baixo',
    statusDoRisco: 'Em Tratamento',
    responsavelPeloRisco: 'Gustavo Paes',
    dataDaUltimaRevisao: '2024-07-28',
    dataDaProximaRevisao: '2024-08-28',
  }
];

const getStatusCounts = (risks: Risk[]) => {
  const counts: { [key in Risk['statusDoRisco']]: number } = {
    'Aberto': 0,
    'Em Tratamento': 0,
    'Fechado': 0,
    'Mitigado': 0,
  };
  risks.forEach(risk => {
    if (counts.hasOwnProperty(risk.statusDoRisco)) {
      counts[risk.statusDoRisco]++;
    }
  });
  return counts;
};

const statusCounts = getStatusCounts(risksData);

export const statusBreakdownChartData = [
  { name: 'Aberto', value: statusCounts['Aberto'], fill: 'hsl(var(--chart-2))' },
  { name: 'Em Tratamento', value: statusCounts['Em Tratamento'], fill: 'hsl(var(--chart-1))' },
  { name: 'Mitigado', value: statusCounts['Mitigado'], fill: 'hsl(var(--chart-3))' },
  { name: 'Fechado', value: statusCounts['Fechado'], fill: 'hsl(var(--muted-foreground))' },
];


export const bowtieData: BowtieData = {
    event: {
        label: "Descarrilamento em Curva",
        description: "Saída do trem dos trilhos em uma curva de raio reduzido.",
    },
    threats: [
        { label: "Velocidade Inadequada", description: "Operação acima da velocidade máxima do trecho." },
        { label: "Desgaste Excessivo do Trilho", description: "Componente da via permanente fora das tolerâncias." },
        { label: "Falha de Material Rodante", description: "Quebra de componente do vagão ou locomotiva." },
    ],
    preventiveControls: [
        { label: "Controle de Velocidade (ATC)", description: "Sistema embarcado que limita a velocidade." },
        { label: "Inspeção de Via Ultrassônica", description: "Detecção de defeitos internos nos trilhos." },
        { label: "Manutenção Preditiva da Frota", description: "Análise de dados para prever falhas em componentes." },
    ],
    consequences: [
        { label: "Danos à Carga e Ativos", description: "Avaria ou perda total da carga e do material rodante." },
        { label: "Impacto Ambiental", description: "Vazamento de produtos perigosos transportados." },
        { label: "Interdição da Via", description: "Bloqueio da linha para reparos, causando atrasos." },
    ],
    mitigatoryControls: [
        { label: "Plano de Atendimento a Emergências", description: "Acionamento rápido de equipes para contenção." },
        { label: "Kits de Mitigação Ambiental", description: "Materiais para contenção de vazamentos e proteção." },
        { label: "Equipe de Restabelecimento", description: "Equipe especializada para liberar a via rapidamente." },
    ]
};
