

import type { Risk, RecentActivity, BowtieData, BowtieThreat, BowtieConsequence, Control, Kpi } from './types';

export const kpisData: Kpi[] = [
    { id: "KPI-1", controlId: 1, frequencia: "Mensal", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-07-30", diasPendentes: -25, status: "Pendente", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-2", controlId: 2, frequencia: "Mensal", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-08-01", diasPendentes: -27, status: "Atrasado", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-3", controlId: 3, frequencia: "Semestral", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-12-28", diasPendentes: -146, status: "Pendente", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-4", controlId: 4, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-5", controlId: 5, frequencia: "Mensal", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-07-29", diasPendentes: -24, status: "Pendente", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-6", controlId: 6, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" },
    { id: "KPI-7", controlId: 7, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Bruno Edison Silva Dalosto", emailResponsavel: "bruno.dalosto@rumolog.com" },
    { id: "KPI-8", controlId: 8, frequencia: "Mensal", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-08-01", diasPendentes: -27, status: "Atrasado", responsavel: "Bruno Edison Silva Dalosto", emailResponsavel: "bruno.dalosto@rumolog.com" },
    { id: "KPI-9", controlId: 9, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-10", controlId: 10, frequencia: "Mensal", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-08-01", diasPendentes: -27, status: "Atrasado", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-11", controlId: 11, frequencia: "Mensal", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-07-30", diasPendentes: -25, status: "Pendente", responsavel: "Victor Dimitri Zolotareff", emailResponsavel: "victor.zolotareff@rumolog.com" },
    { id: "KPI-12", controlId: 12, frequencia: "Semestral", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-12-28", diasPendentes: -146, status: "Pendente", responsavel: "Victor Dimitri Zolotareff", emailResponsavel: "victor.zolotareff@rumolog.com" },
    { id: "KPI-13", controlId: 13, frequencia: "Trimestral", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-10-01", diasPendentes: -88, status: "Atrasado", responsavel: "Bruno Edison Silva Dalosto", emailResponsavel: "bruno.dalosto@rumolog.com" },
    { id: "KPI-14", controlId: 14, frequencia: "Mensal", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-07-30", diasPendentes: -25, status: "Pendente", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-15", controlId: 15, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Pablo Lacerda Aguiar", emailResponsavel: "pablo.aguiar@rumolog.com" },
    { id: "KPI-16", controlId: 16, frequencia: "Trimestral", ultimoKpiInformado: undefined, prazoProximoRegistro: "2024-09-30", diasPendentes: -87, status: "Pendente", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-17", controlId: 17, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" },
    { id: "KPI-18", controlId: 18, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Bruno Edison Silva Dalosto", emailResponsavel: "bruno.dalosto@rumolog.com" },
    { id: "KPI-19", controlId: 19, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-20", controlId: 20, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Victor Dimitri Zolotareff", emailResponsavel: "victor.zolotareff@rumolog.com" },
    { id: "KPI-21", controlId: 21, frequencia: "Mensal", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-08-01", diasPendentes: -27, status: "Atrasado", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-22", controlId: 22, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Victor Dimitri Zolotareff", emailResponsavel: "victor.zolotareff@rumolog.com" },
    { id: "KPI-23", controlId: 23, frequencia: "Mensal", ultimoKpiInformado: "2024-07-02", prazoProximoRegistro: "2024-08-01", diasPendentes: -27, status: "Atrasado", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" },
    { id: "KPI-24", controlId: 24, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" },
    { id: "KPI-25", controlId: 25, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" },
    { id: "KPI-26", controlId: 26, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Kaio Coutinho de Farias", emailResponsavel: "kaio.farias@rumolog.com" },
    { id: "KPI-27", controlId: 27, frequencia: "Anual", ultimoKpiInformado: undefined, prazoProximoRegistro: "2025-06-30", diasPendentes: -360, status: "Pendente", responsavel: "Edson Yassuo Abe", emailResponsavel: "edson.abe@rumolog.com" }
];

export const controlsData: Control[] = [
    {
        criadoEm: '2024-06-24',
        id: 1,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-01',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Plano de Inspeção e Limpeza das Estruturas',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementação Futura',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-05',
        frequenciaMeses: 6,
        proximaVerificacao: '2024-12-02',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-01 Inspeção Limpeza',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;RUBENS.ALENCAR@RUMOLOG.COM;CS264288@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 30,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 2,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-02',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'SPDA - Aterramento dos Silos, Armazéns e Equipamentos',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado com Pendência',
        donoControle: 'Pablo Lacerda Aguiar',
        emailDono: 'pablo.aguiar@rumolog.com',
        area: 'MANUTENÇÃO',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-02 SPDA',
        evidencia: 'E-LDT-RMO-02202-001-00 - LAUDO ATERRAMENTO E SPDA TRO',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 30,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 3,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-03',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Instalação elétrica adequada e classificação de área',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementação Futura',
        donoControle: 'Bruno Edison Silva Dalosto',
        emailDono: 'bruno.dalosto@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 6,
        proximaVerificacao: '2024-11-30',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-03  Área classificada',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;CS306132@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 30,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 4,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-04',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Dispositivo de Supressão de Pó',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Não Implementado',
        donoControle: 'Pablo Lacerda Aguiar',
        emailDono: 'pablo.aguiar@rumolog.com',
        area: 'MANUTENÇÃO',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-04 Supressão de Pó',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 30,
        criticidade: 'Sim',
    },
     {
        criadoEm: '2024-06-24',
        id: 5,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-05',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Controle de temperatura em equipamentos e ambientes',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado',
        donoControle: 'Pablo Lacerda Aguiar',
        emailDono: 'pablo.aguiar@rumolog.com',
        area: 'MANUTENÇÃO',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-10',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-05 Controle de Temp.',
        evidencia: 'Planilhas de medição',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 30,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 6,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-06',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Procedimento de trabalho a quente',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-01-20',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-01-15',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-06 Trab. Quente',
        evidencia: 'IT-CORP-SEG-000',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;edson.abe@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 30,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 7,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-07',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Treinamento de Brigada de Emergência',
        tipo: 'Mitigatório',
        classificacao: 'Pessoa',
        status: 'Implementado',
        donoControle: 'Bruno Edison Silva Dalosto',
        emailDono: 'bruno.dalosto@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-05-15',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-10',
        validacao: 'DENTRO DO PRAZO',
        onePager: '01-07 Brigada',
        evidencia: 'Lista de Presença',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 30,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 8,
        codigoMUE: 'RUMO 01',
        titulo: 'RUMO 01-08',
        idRiscoMUE: 30,
        descricaoMUE: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)',
        nomeControle: 'Inspeção e manutenção de sistemas de combate a incêndio',
        tipo: 'Mitigatório',
        classificacao: 'Equipamento',
        status: 'Implementado com Pendência',
        donoControle: 'Bruno Edison Silva Dalosto',
        emailDono: 'bruno.dalosto@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-01',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-01',
        validacao: 'ATRASADO',
        onePager: '01-08 Insp. Incendio',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 30,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 9,
        codigoMUE: 'RUMO 02',
        titulo: 'RUMO 02-01',
        idRiscoMUE: 29,
        descricaoMUE: 'Colapso de estrutura (silo, armazém, torre de elevador, moega)',
        nomeControle: 'Inspeção predial em estruturas de concreto e metálicas',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Pablo Lacerda Aguiar',
        emailDono: 'pablo.aguiar@rumolog.com',
        area: 'MANUTENÇÃO',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '02-01 Insp Predial',
        evidencia: 'Laudos de Inspeção',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 29,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 10,
        codigoMUE: 'RUMO 02',
        titulo: 'RUMO 02-02',
        idRiscoMUE: 29,
        descricaoMUE: 'Colapso de estrutura (silo, armazém, torre de elevador, moega)',
        nomeControle: 'Monitoramento de Recalque e Verticalidade',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Não Implementado',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-05',
        frequenciaMeses: 6,
        proximaVerificacao: '2024-12-02',
        validacao: 'DENTRO DO PRAZO',
        onePager: '02-02 Monit Recalque',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 29,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 11,
        codigoMUE: 'RUMO 03',
        titulo: 'RUMO 03-01',
        idRiscoMUE: 2,
        descricaoMUE: 'Descarrilamento em AMV durante manobra de entrada/saída do terminal',
        nomeControle: 'Inspeção de AMVs',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado com Pendência',
        donoControle: 'Victor Dimitri Zolotareff',
        emailDono: 'victor.zolotareff@rumolog.com',
        area: 'VIA PERMANENTE',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-01',
        validacao: 'ATRASADO',
        onePager: '03-01 Insp AMV',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 2,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 12,
        codigoMUE: 'RUMO 03',
        titulo: 'RUMO 03-02',
        idRiscoMUE: 2,
        descricaoMUE: 'Descarrilamento em AMV durante manobra de entrada/saída do terminal',
        nomeControle: 'Manutenção de AMVs',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Não Implementado',
        donoControle: 'Victor Dimitri Zolotareff',
        emailDono: 'victor.zolotareff@rumolog.com',
        area: 'VIA PERMANENTE',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-01',
        validacao: 'ATRASADO',
        onePager: '03-02 Manut AMV',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 2,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 13,
        codigoMUE: 'RUMO 04',
        titulo: 'RUMO 04-01',
        idRiscoMUE: 1,
        descricaoMUE: 'Queda de pessoa ou objeto de passarela/plataforma/escada',
        nomeControle: 'Inspeção de Guarda Corpo',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado com Pendência',
        donoControle: 'Bruno Edison Silva Dalosto',
        emailDono: 'bruno.dalosto@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 3,
        proximaVerificacao: '2024-09-01',
        validacao: 'DENTRO DO PRAZO',
        onePager: '04-01 Insp Guarda Corpo',
        evidencia: 'Checklist de Inspeção',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: 1,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 14,
        codigoMUE: 'RUMO 05',
        titulo: 'RUMO 05-01',
        idRiscoMUE: 18,
        descricaoMUE: 'Contaminação de produto (soja/farelo/milho)',
        nomeControle: 'Controle de qualidade de produto',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado com Pendência',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-10',
        validacao: 'DENTRO DO PRAZO',
        onePager: '05-01 Qualidade',
        evidencia: 'Relatórios de Análise',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Comercial',
        topRiskAssociado: 'Risco 04.Perdas ou danos ao produto',
        idRiscos: 18,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 15,
        codigoMUE: 'RUMO 06',
        titulo: 'RUMO 06-01',
        idRiscoMUE: 14,
        descricaoMUE: 'Exposição a produto químico durante operação de fumigação/expurgo',
        nomeControle: 'Procedimento de Fumigação/Expurgo',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Pablo Lacerda Aguiar',
        emailDono: 'pablo.aguiar@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '06-01 Proc Fumigação',
        evidencia: 'IT-CORP-SEG-0XX',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: 14,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 16,
        codigoMUE: 'RUMO 07',
        titulo: 'RUMO 07-01',
        idRiscoMUE: 21,
        descricaoMUE: 'Vazamento de produtos perigosos em bacias de contenção',
        nomeControle: 'Inspeção e Manutenção de Bacias de Contenção',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado com Pendência',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-05',
        frequenciaMeses: 3,
        proximaVerificacao: '2024-09-03',
        validacao: 'DENTRO DO PRAZO',
        onePager: '07-01 Bacias Contenção',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Meio Ambiente',
        topRiskAssociado: 'Risco 03.Dano ambiental e/ou à comunidade',
        idRiscos: 21,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 17,
        codigoMUE: 'RUMO 08',
        titulo: 'RUMO 08-01',
        idRiscoMUE: 13,
        descricaoMUE: 'Atropelamento em cruzamento rodoferroviário',
        nomeControle: 'Manutenção da Sinalização Passiva em PN',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'VIA PERMANENTE',
        dataUltimaVerificacao: '2024-01-20',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-01-15',
        validacao: 'DENTRO DO PRAZO',
        onePager: '08-01 Manut Sinalização',
        evidencia: 'IT-CORP-SEG-000',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;edson.abe@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: 13,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 18,
        codigoMUE: 'RUMO 08',
        titulo: 'RUMO 08-02',
        idRiscoMUE: 13,
        descricaoMUE: 'Atropelamento em cruzamento rodoferroviário',
        nomeControle: 'Manutenção da Sinalização Ativa em PN',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado',
        donoControle: 'Bruno Edison Silva Dalosto',
        emailDono: 'bruno.dalosto@rumolog.com',
        area: 'VIA PERMANENTE',
        dataUltimaVerificacao: '2024-05-15',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-10',
        validacao: 'DENTRO DO PRAZO',
        onePager: '08-02 Manut Sinalização Ativa',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: 13,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 19,
        codigoMUE: 'RUMO 08',
        titulo: 'RUMO 08-03',
        idRiscoMUE: 13,
        descricaoMUE: 'Atropelamento em cruzamento rodoferroviário',
        nomeControle: 'Campanha de Conscientização em PN',
        tipo: 'Preventivo',
        classificacao: 'Pessoa',
        status: 'Implementado',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-01',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-28',
        validacao: 'DENTRO DO PRAZO',
        onePager: '08-03 Campanha PN',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: 13,
        criticidade: 'Não',
    },
    {
        criadoEm: '2024-06-24',
        id: 20,
        codigoMUE: 'RUMO 09',
        titulo: 'RUMO 09-01',
        idRiscoMUE: 27,
        descricaoMUE: 'Engolfamento em espaço confinado (silo, secador, poço de elevador)',
        nomeControle: 'Permissão de Entrada e Trabalho em Espaço Confinado (PET)',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Victor Dimitri Zolotareff',
        emailDono: 'victor.zolotareff@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '09-01 PET',
        evidencia: 'IT-CORP-SEG-00Y',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;pablo.aguiar@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: 27,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 21,
        codigoMUE: 'RUMO 09',
        titulo: 'RUMO 09-02',
        idRiscoMUE: 27,
        descricaoMUE: 'Engolfamento em espaço confinado (silo, secador, poço de elevador)',
        nomeControle: 'Bloqueio de energias perigosas',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-05',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '09-02 Bloqueio',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: 27,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 22,
        codigoMUE: 'RUMO 09',
        titulo: 'RUMO 09-03',
        idRiscoMUE: 27,
        descricaoMUE: 'Engolfamento em espaço confinado (silo, secador, poço de elevador)',
        nomeControle: 'Treinamento de equipes de resgate e salvamento',
        tipo: 'Mitigatório',
        classificacao: 'Pessoa',
        status: 'Implementado',
        donoControle: 'Victor Dimitri Zolotareff',
        emailDono: 'victor.zolotareff@rumolog.com',
        area: 'SEGURANÇA',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-31',
        validacao: 'DENTRO DO PRAZO',
        onePager: '09-03 Treinamento',
        evidencia: 'IT-CORP-SEG-00Z',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: 27,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 23,
        codigoMUE: 'RUMO 10',
        titulo: 'RUMO 10-01',
        idRiscoMUE: 25,
        descricaoMUE: 'Assalto a carga em movimento ou parada',
        nomeControle: 'Monitoramento de Trens e Alertas de Parada',
        tipo: 'Preventivo',
        classificacao: 'Sistema',
        status: 'Implementado com Pendência',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'OPERAÇÃO',
        dataUltimaVerificacao: '2024-06-03',
        frequenciaMeses: 1,
        proximaVerificacao: '2024-07-01',
        validacao: 'ATRASADO',
        onePager: '10-01 Monitoramento',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 04.Perdas ou danos ao produto',
        idRiscos: 25,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 24,
        codigoMUE: 'RUMO 10',
        titulo: 'RUMO 10-02',
        idRiscoMUE: 25,
        descricaoMUE: 'Assalto a carga em movimento ou parada',
        nomeControle: 'Escolta de trens em trechos críticos',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'SEGURANÇA PATRIMONIAL',
        dataUltimaVerificacao: '2024-01-20',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-01-15',
        validacao: 'DENTRO DO PRAZO',
        onePager: '10-02 Escolta',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;edson.abe@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 04.Perdas ou danos ao produto',
        idRiscos: 25,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 25,
        codigoMUE: 'RUMO 10',
        titulo: 'RUMO 10-03',
        idRiscoMUE: 25,
        descricaoMUE: 'Assalto a carga em movimento ou parada',
        nomeControle: 'Comunicação com autoridades policiais',
        tipo: 'Mitigatório',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'SEGURANÇA PATRIMONIAL',
        dataUltimaVerificacao: '2024-05-15',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-10',
        validacao: 'DENTRO DO PRAZO',
        onePager: '10-03 Comunicação',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;bruno.dalosto@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 04.Perdas ou danos ao produto',
        idRiscos: 25,
        criticidade: 'Não',
    },
    {
        criadoEm: '2024-06-24',
        id: 26,
        codigoMUE: 'RUMO 11',
        titulo: 'RUMO 11-01',
        idRiscoMUE: 28,
        descricaoMUE: 'Danos a equipamentos por descarga atmosférica',
        nomeControle: 'SPDA - Sistema de Proteção contra Descargas Atmosféricas',
        tipo: 'Preventivo',
        classificacao: 'Equipamento',
        status: 'Implementado com Pendência',
        donoControle: 'Kaio Coutinho de Farias',
        emailDono: 'kaio.farias@rumolog.com',
        area: 'MANUTENÇÃO',
        dataUltimaVerificacao: '2024-06-01',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-05-28',
        validacao: 'DENTRO DO PRAZO',
        onePager: '11-01 SPDA',
        evidencia: 'Laudo de SPDA',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;kaio.farias@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 01.Não integridade Operacional de Ativos',
        idRiscos: 28,
        criticidade: 'Sim',
    },
    {
        criadoEm: '2024-06-24',
        id: 27,
        codigoMUE: 'RUMO 12',
        titulo: 'RUMO 12-01',
        idRiscoMUE: 22,
        descricaoMUE: 'Invasão à área operacional por pessoas não autorizadas',
        nomeControle: 'Controle de Acesso de Pessoas e Veículos',
        tipo: 'Preventivo',
        classificacao: 'Procedimento',
        status: 'Implementado',
        donoControle: 'Edson Yassuo Abe',
        emailDono: 'edson.abe@rumolog.com',
        area: 'SEGURANÇA PATRIMONIAL',
        dataUltimaVerificacao: '2024-06-10',
        frequenciaMeses: 12,
        proximaVerificacao: '2025-06-05',
        validacao: 'DENTRO DO PRAZO',
        onePager: '12-01 Controle Acesso',
        evidencia: '',
        criadoPor: 'Aluisio Fernando de Oliveira Filho',
        modificadoEm: '2024-08-26',
        modificadoPor: 'Victor Dimitri Zolotareff',
        preenchimentoKPI: 'CS337482@rumolog.com;edson.abe@rumolog.com',
        gerenciaRisco: 'Operação',
        topRiskAssociado: 'Risco 02.Acidente com fatalidade ou incapacitante',
        idRiscos: 22,
        criticidade: 'Sim',
    },
];

export const risksData: Risk[] = [
  { id: '1', gerencia: 'Operação', topRiskAssociado: 'Quedas de Risco OLN Operacional', categoriaMP: '10', orig: 8, prob: 7, ctrl: 7, tempo: 10, facil: 8, elev: 815, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Guilherme', v: 9, d: 6.5, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 9, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Crítico', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '5.2 Governança', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-CR-Negócio', tronco: '1.3 Paralis', englobado: 'Curto Prazo', fatorDeRisco: 'Material Rodante', horizonte: 'Curto Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '70%', processo: 'OP-Processo', diretoria: 'OP-Diretoria', risco: 'Queda de pessoa ou objeto de passarela/plataforma/escada', descricaoDoRisco: 'Risco de queda de pessoas ou objetos de locais elevados como passarelas, plataformas ou escadas, podendo resultar em lesões graves ou fatalidades.', dataDeIdentificacao: '2023-01-01', causaRaizDoRisco: 'Falha em guarda-corpo, piso escorregadio, falta de atenção, ausência de EPI.', consequenciaDoRisco: 'Lesões graves, fatalidades, interrupção da operação, danos à reputação.', processoAfetado: 'Manutenção, Operação, Inspeção', descricaoDoControle: 'Controle do Risco 1', statusDoRisco: 'Aberto', planoDeAcao: 'PA-001', dataDaUltimaRevisao: '2024-07-01', dataDaProximaRevisao: '2025-01-01', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Possível', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Alto' },
  { id: '2', gerencia: 'Tecnologia', topRiskAssociado: 'Comprometimento de Risco 07. I. Tecnológico', categoriaMP: '10', orig: 9, prob: 8, ctrl: 8, tempo: 6, facil: 8, elev: 805, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Silvio Hesi', v: 9.5, d: 8, g: 0, u: 0, t_score: 8, i_score: 0, oredsX: 9.5, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Crítico', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'E - Ambiental', pilarESG: 'S - Social', indicador: '2.1 Licenciamento', subtema: 'Integridade Tecnológica', categoriaDoRisco: 'RISK-TC-Negócio', tronco: '7.1 Inclusão', englobado: 'Longo Prazo', fatorDeRisco: 'Tecnologia e Segurança da Informação', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '40%', processo: 'TI-Processo', diretoria: 'TI-Diretoria', risco: 'Descarrilamento em AMV durante manobra de entrada/saída do terminal', descricaoDoRisco: 'Risco de descarrilamento de vagões ou locomotivas em Aparelhos de Mudança de Via (AMV) durante operações de manobra, com potencial para causar danos materiais e interrupções.', dataDeIdentificacao: '2023-01-02', causaRaizDoRisco: 'Falha no AMV, erro operacional, velocidade excessiva, condição inadequada da via.', consequenciaDoRisco: 'Danos ao material rodante, bloqueio da linha, atrasos na operação, custos de reparo.', processoAfetado: 'Operação de Pátio, Manutenção de Via', descricaoDoControle: 'Controle do Risco 2', statusDoRisco: 'Em Tratamento', planoDeAcao: 'PA-002', dataDaUltimaRevisao: '2024-07-02', dataDaProximaRevisao: '2025-01-02', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Catastrófico', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Provável', impactoResidual: 'Maior', nivelDeRiscoResidual: 'Crítico' },
  { id: '3', gerencia: 'Operação', topRiskAssociado: 'Anos de va Risco OLN Operacional', categoriaMP: '10', orig: 8, prob: 10, ctrl: 8, tempo: 4, facil: 8, elev: 800, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Guilherme', v: 8, d: 9, g: 0, u: 0, t_score: 8, i_score: 0, oredsX: 8, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Em Andamento', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'S - Social', pilarESG: 'S - Social', indicador: '8.2 Relacionamento', subtema: 'Integridade Operacional', categoriaDoRisco: 'RISK-OPA-Negócio', tronco: '1.1 Paralis', englobado: 'Curto Prazo', fatorDeRisco: 'Segurança e Riscos Operacionais', horizonte: 'Curto Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '100%', processo: 'OP-Processo', diretoria: 'OP-Diretoria', risco: 'Risco 3', descricaoDoRisco: 'Descrição do Risco 3', dataDeIdentificacao: '2023-01-03', causaRaizDoRisco: 'Causa do Risco 3', consequenciaDoRisco: 'Consequência do Risco 3', processoAfetado: 'Processo Afetado 3', descricaoDoControle: 'Controle do Risco 3', statusDoRisco: 'Fechado', planoDeAcao: 'PA-003', dataDaUltimaRevisao: '2024-07-03', dataDaProximaRevisao: '2025-01-03', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Provável', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Alto' },
  { id: '4', gerencia: 'Tecnologia', topRiskAssociado: 'Ausência de Risco 07. I. Tecnológico', categoriaMP: '8', orig: 6, prob: 2, ctrl: 8, tempo: 4, facil: 4, elev: 490, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Anna Neta', v: 7, d: 3, g: 0, u: 0, t_score: 9, i_score: 0, oredsX: 7, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'sim', riscosMix: 'não', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '3.4 Segurança', subtema: 'Integridade Regulatória', categoriaDoRisco: 'RISK-REG-Negócio', tronco: '7.4 Acessos', englobado: 'Curto Prazo', fatorDeRisco: 'Material Rodante', horizonte: 'Curto Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '100%', processo: 'REG-Processo', diretoria: 'REG-Diretoria', risco: 'Risco 4', descricaoDoRisco: 'Descrição do Risco 4', dataDeIdentificacao: '2023-01-04', causaRaizDoRisco: 'Causa do Risco 4', consequenciaDoRisco: 'Consequência do Risco 4', processoAfetado: 'Processo Afetado 4', descricaoDoControle: 'Controle do Risco 4', statusDoRisco: 'Mitigado', planoDeAcao: 'PA-004', dataDaUltimaRevisao: '2024-07-04', dataDaProximaRevisao: '2025-01-04', ier: 0, probabilidadeInerente: 'Improvável', impactoInerente: 'Moderado', nivelDeRiscoInerente: 'Médio', probabilidadeResidual: 'Raro', impactoResidual: 'Insignificante', nivelDeRiscoResidual: 'Baixo' },
  { id: '5', gerencia: 'Operação', topRiskAssociado: 'Colapso em Risco OLN Operacional', categoriaMP: '10', orig: 8, prob: 4, ctrl: 7, tempo: 10, facil: 8, elev: 770, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Guilherme', v: 8.5, d: 7, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 8.5, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '3.3 Reputação', subtema: 'Integridade Financeira', categoriaDoRisco: 'RISK-FIN-Negócio', tronco: '1.3 Paralis', englobado: 'Curto Prazo', fatorDeRisco: 'Material Rodante', horizonte: 'Curto Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '80%', processo: 'FIN-Processo', diretoria: 'FIN-Diretoria', risco: 'Risco 5', descricaoDoRisco: 'Descrição do Risco 5', dataDeIdentificacao: '2023-01-05', causaRaizDoRisco: 'Causa do Risco 5', consequenciaDoRisco: 'Consequência do Risco 5', processoAfetado: 'Processo Afetado 5', descricaoDoControle: 'Controle do Risco 5', statusDoRisco: 'Aberto', planoDeAcao: 'PA-005', dataDaUltimaRevisao: '2024-07-05', dataDaProximaRevisao: '2025-01-05', ier: 0, probabilidadeInerente: 'Possível', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Alto', probabilidadeResidual: 'Raro', impactoResidual: 'Menor', nivelDeRiscoResidual: 'Baixo' },
  { id: '6', gerencia: 'Tecnologia', topRiskAssociado: 'Comprometimento de Risco 07. I. Tecnológico', categoriaMP: '9', orig: 8, prob: 2, ctrl: 4, tempo: 4, facil: 6, elev: 555, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Silvio Hesi', v: 8.5, d: 1, g: 0, u: 0, t_score: 9, i_score: 0, oredsX: 8.5, t_rating: 0, riscosAceitaveis: 'sim', riscosNaoAceitaveis: 'não', riscosMix: 'não', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'E - Ambiental', pilarESG: 'S - Social', indicador: '4.1 Denos', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-AMB-Negócio', tronco: '7.1 Inclusão', englobado: 'Longo Prazo', fatorDeRisco: 'Meio Ambiente', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'AMB-Processo', diretoria: 'AMB-Diretoria', risco: 'Risco 6', descricaoDoRisco: 'Descrição do Risco 6', dataDeIdentificacao: '2023-01-06', causaRaizDoRisco: 'Causa do Risco 6', consequenciaDoRisco: 'Consequência do Risco 6', processoAfetado: 'Processo Afetado 6', descricaoDoControle: 'Controle do Risco 6', statusDoRisco: 'Em Tratamento', planoDeAcao: 'PA-006', dataDaUltimaRevisao: '2024-07-06', dataDaProximaRevisao: '2025-01-06', ier: 0, probabilidadeInerente: 'Improvável', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Médio', probabilidadeResidual: 'Raro', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Médio' },
  { id: '7', gerencia: 'Ambiental', topRiskAssociado: 'Risco Risco 04. I. Tecnológico', categoriaMP: '10', orig: 2, prob: 6, ctrl: 6, tempo: 6, facil: 8, elev: 750, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Guilherme', v: 9, d: 7, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 9, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Geral', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'E - Ambiental', pilarESG: 'S - Social', indicador: '4.1 Denos', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-TEC-Negócio', tronco: '7.1 Inclusão', englobado: 'Longo Prazo', fatorDeRisco: 'Meio Ambiente', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'TEC-Processo', diretoria: 'TEC-Diretoria', risco: 'Risco 7', descricaoDoRisco: 'Descrição do Risco 7', dataDeIdentificacao: '2023-01-07', causaRaizDoRisco: 'Causa do Risco 7', consequenciaDoRisco: 'Consequência do Risco 7', processoAfetado: 'Processo Afetado 7', descricaoDoControle: 'Controle do Risco 7', statusDoRisco: 'Fechado', planoDeAcao: 'PA-007', dataDaUltimaRevisao: '2024-07-07', dataDaProximaRevisao: '2025-01-07', ier: 0, probabilidadeInerente: 'Provável', impactoInerente: 'Insignificante', nivelDeRiscoInerente: 'Médio', probabilidadeResidual: 'Possível', impactoResidual: 'Insignificante', nivelDeRiscoResidual: 'Baixo' },
  { id: '8', gerencia: 'Tecnologia', topRiskAssociado: 'Ausência de Risco 07. I. Tecnológico', categoriaMP: '3', orig: 8, prob: 2, ctrl: 2, tempo: 4, facil: 2, elev: 360, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Silvio Hesi', v: 3.5, d: 2, g: 0, u: 0, t_score: 2, i_score: 0, oredsX: 3.5, t_rating: 0, riscosAceitaveis: 'sim', riscosNaoAceitaveis: 'não', riscosMix: 'não', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Crítico', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'E - Ambiental', pilarESG: 'S - Social', indicador: '7.2 Denos', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-TEC-Negócio', tronco: '7.1 Inclusão', englobado: 'Longo Prazo', fatorDeRisco: 'Tecnologia e Segurança da Informação', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'TEC-Processo', diretoria: 'TEC-Diretoria', risco: 'Risco 8', descricaoDoRisco: 'Descrição do Risco 8', dataDeIdentificacao: '2023-01-08', causaRaizDoRisco: 'Causa do Risco 8', consequenciaDoRisco: 'Consequência do Risco 8', processoAfetado: 'Processo Afetado 8', descricaoDoControle: 'Controle do Risco 8', statusDoRisco: 'Mitigado', planoDeAcao: 'PA-008', dataDaUltimaRevisao: '2024-07-08', dataDaProximaRevisao: '2025-01-08', ier: 0, probabilidadeInerente: 'Improvável', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Médio', probabilidadeResidual: 'Raro', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Médio' },
  { id: '9', gerencia: 'Tecnologia', topRiskAssociado: 'Segmentos de Risco 07. I. Tecnológico', categoriaMP: '10', orig: 8, prob: 7, ctrl: 7, tempo: 7, facil: 8, elev: 800, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Silvio Hesi', v: 9, d: 7.5, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 9, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Crítico', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'E - Ambiental', pilarESG: 'S - Social', indicador: '7.4 Acessos', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-TEC-Negócio', tronco: '7.4 Acessos', englobado: 'Curto Prazo', fatorDeRisco: 'Material Rodante', horizonte: 'Curto Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'TEC-Processo', diretoria: 'TEC-Diretoria', risco: 'Risco 9', descricaoDoRisco: 'Descrição do Risco 9', dataDeIdentificacao: '2023-01-09', causaRaizDoRisco: 'Causa do Risco 9', consequenciaDoRisco: 'Consequência do Risco 9', processoAfetado: 'Processo Afetado 9', descricaoDoControle: 'Controle do Risco 9', statusDoRisco: 'Aberto', planoDeAcao: 'PA-009', dataDaUltimaRevisao: '2024-07-09', dataDaProximaRevisao: '2025-01-09', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Possível', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Alto' },
  { id: '10', gerencia: 'Tecnologia', topRiskAssociado: 'Gestão de Risco 07. I. Tecnológico', categoriaMP: '8', orig: 8, prob: 7, ctrl: 7, tempo: 6, facil: 8, elev: 735, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Anna Neta', v: 9, d: 7.5, g: 0, u: 0, t_score: 8, i_score: 0, oredsX: 9, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Em Andamento', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '1.3 Paralis', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-TEC-Negócio', tronco: '7.1 Inclusão', englobado: 'Longo Prazo', fatorDeRisco: 'Tecnologia e Segurança da Informação', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'TEC-Processo', diretoria: 'TEC-Diretoria', risco: 'Risco 10', descricaoDoRisco: 'Descrição do Risco 10', dataDeIdentificacao: '2023-01-10', causaRaizDoRisco: 'Causa do Risco 10', consequenciaDoRisco: 'Consequência do Risco 10', processoAfetado: 'Processo Afetado 10', descricaoDoControle: 'Controle do Risco 10', statusDoRisco: 'Em Tratamento', planoDeAcao: 'PA-010', dataDaUltimaRevisao: '2024-07-10', dataDaProximaRevisao: '2025-01-10', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Possível', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Alto' },
  { id: '11', gerencia: 'Operação', topRiskAssociado: 'Acidentes Risco OLN Operacional', categoriaMP: '7', orig: 6, prob: 10, ctrl: 8, tempo: 4, facil: 8, elev: 725, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Guilherme', v: 6.5, d: 9, g: 0, u: 0, t_score: 8, i_score: 0, oredsX: 6.5, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Negócio', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '1.3 Paralis', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-OPE-Negócio', tronco: '1.3 Paralis', englobado: 'Curto Prazo', fatorDeRisco: 'Segurança e Riscos Operacionais', horizonte: 'Curto Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'OPE-Processo', diretoria: 'OPE-Diretoria', risco: 'Risco 11', descricaoDoRisco: 'Descrição do Risco 11', dataDeIdentificacao: '2023-01-11', causaRaizDoRisco: 'Causa do Risco 11', consequenciaDoRisco: 'Consequência do Risco 11', processoAfetado: 'Processo Afetado 11', descricaoDoControle: 'Controle do Risco 11', statusDoRisco: 'Fechado', planoDeAcao: 'PA-011', dataDaUltimaRevisao: '2024-07-11', dataDaProximaRevisao: '2025-01-11', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Moderado', nivelDeRiscoInerente: 'Alto', probabilidadeResidual: 'Provável', impactoResidual: 'Menor', nivelDeRiscoResidual: 'Alto' },
  { id: '12', gerencia: 'Tecnologia', topRiskAssociado: 'Falha Crítica Risco 07. I. Tecnológico', categoriaMP: '8', orig: 7, prob: 2, ctrl: 6, tempo: 6, facil: 8, elev: 825, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Silvio Hesi', v: 7.5, d: 4, g: 0, u: 0, t_score: 8, i_score: 0, oredsX: 7.5, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Negócio', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'L - Ambiental', pilarESG: 'S - Social', indicador: '1.1 Danos', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-TEC-Negócio', tronco: '7.1 Inclusão', englobado: 'Longo Prazo', fatorDeRisco: 'Material Rodante', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'TEC-Processo', diretoria: 'TEC-Diretoria', risco: 'Risco 12', descricaoDoRisco: 'Descrição do Risco 12', dataDeIdentificacao: '2023-01-12', causaRaizDoRisco: 'Causa do Risco 12', consequenciaDoRisco: 'Consequência do Risco 12', processoAfetado: 'Processo Afetado 12', descricaoDoControle: 'Controle do Risco 12', statusDoRisco: 'Mitigado', planoDeAcao: 'PA-012', dataDaUltimaRevisao: '2024-07-12', dataDaProximaRevisao: '2025-01-12', ier: 0, probabilidadeInerente: 'Improvável', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Médio', probabilidadeResidual: 'Raro', impactoResidual: 'Menor', nivelDeRiscoResidual: 'Baixo' },
  { id: '13', gerencia: 'GesMud', topRiskAssociado: 'Gestão Integrada Risco 11. I. Operacional', categoriaMP: '12', orig: 10, prob: 8, ctrl: 8, tempo: 10, facil: 5, elev: 710, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Clavile', v: 0, d: 5.5, g: 0, u: 0, t_score: 0, i_score: 0, oredsX: 0, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Negócio', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '11.1 Desvio', subtema: 'Não Aplicável', categoriaDoRisco: 'RISK-MUD-Negócio', tronco: '11.1 Desvio', englobado: 'Curto Prazo', fatorDeRisco: 'Controles Internos', horizonte: 'Curto Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'MUD-Processo', diretoria: 'MUD-Diretoria', risco: 'Risco 13', descricaoDoRisco: 'Descrição do Risco 13', dataDeIdentificacao: '2023-01-13', causaRaizDoRisco: 'Causa do Risco 13', consequenciaDoRisco: 'Consequência do Risco 13', processoAfetado: 'Processo Afetado 13', descricaoDoControle: 'Controle do Risco 13', statusDoRisco: 'Aberto', planoDeAcao: 'PA-013', dataDaUltimaRevisao: '2024-07-13', dataDaProximaRevisao: '2025-01-13', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Catastrófico', nivelDeRiscoInerente: 'Extremo', probabilidadeResidual: 'Provável', impactoResidual: 'Maior', nivelDeRiscoResidual: 'Crítico' },
  { id: '14', gerencia: 'Compliance', topRiskAssociado: 'Exposição a produto químico durante operação de fumigação/expurgo', categoriaMP: '8', orig: 8, prob: 10, ctrl: 8, tempo: 8, facil: 5, elev: 710, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Ana Paula', v: 0, d: 5.5, g: 0, u: 0, t_score: 0, i_score: 0, oredsX: 0, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Negócio', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '8.1 Desvio', subtema: 'Governança e Ética', categoriaDoRisco: 'RISK-INT-Negócio', tronco: '8.1 Desvio', englobado: 'Médio Prazo', fatorDeRisco: 'Expansão - Portos e Terminais', horizonte: 'Médio Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'INT-Processo', diretoria: 'INT-Diretoria', risco: 'Exposição a produto químico durante operação de fumigação/expurgo', descricaoDoRisco: 'Risco de exposição de colaboradores a produtos químicos tóxicos durante atividades de fumigação, podendo causar intoxicação aguda ou crônica.', dataDeIdentificacao: '2023-01-14', causaRaizDoRisco: 'Falha no EPI, procedimento inadequado, falta de ventilação, vazamento de equipamento.', consequenciaDoRisco: 'Problemas de saúde graves, afastamento do trabalho, passivos trabalhistas.', processoAfetado: 'Operação de Armazenagem', descricaoDoControle: 'Controle do Risco 14', statusDoRisco: 'Em Tratamento', planoDeAcao: 'PA-014', dataDaUltimaRevisao: '2024-07-14', dataDaProximaRevisao: '2025-01-14', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Provável', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Alto' },
  { id: '15', gerencia: 'Regulatório', topRiskAssociado: 'Descumprimento Risco 03. I. Regulatório', categoriaMP: '9', orig: 10, prob: 5, ctrl: 5, tempo: 5, facil: 6, elev: 710, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Alexandre', v: 9.5, d: 5.5, g: 0, u: 0, t_score: 6.5, i_score: 0, oredsX: 9.5, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Negócio', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '3.2 Decisão', subtema: 'Não Aplicável', categoriaDoRisco: 'RISK-REG-Regulatório', tronco: '3.2 Decisão', englobado: 'Longo Prazo', fatorDeRisco: 'EXP-Projetos de Expansão. Este item está vinculado com o Risco 14', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'REG-Processo', diretoria: 'REG-Diretoria', risco: 'Risco 15', descricaoDoRisco: 'Descrição do Risco 15', dataDeIdentificacao: '2023-01-15', causaRaizDoRisco: 'Causa do Risco 15', consequenciaDoRisco: 'Consequência do Risco 15', processoAfetado: 'Processo Afetado 15', descricaoDoControle: 'Controle do Risco 15', statusDoRisco: 'Fechado', planoDeAcao: 'PA-015', dataDaUltimaRevisao: '2024-07-15', dataDaProximaRevisao: '2025-01-15', ier: 0, probabilidadeInerente: 'Possível', impactoInerente: 'Catastrófico', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Improvável', impactoResidual: 'Maior', nivelDeRiscoResidual: 'Alto' },
  { id: '16', gerencia: 'GesMud', topRiskAssociado: 'Gestão Integrada Risco 11. I. Operacional', categoriaMP: '8', orig: 8, prob: 5, ctrl: 8, tempo: 9, facil: 6, elev: 705, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Clavile', v: 0, d: 6.5, g: 0, u: 0, t_score: 0, i_score: 0, oredsX: 0, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Negócio', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '11.1 Desvio', subtema: 'Não Aplicável', categoriaDoRisco: 'RISK-MUD-Negócio', tronco: '11.1 Desvio', englobado: 'Curto Prazo', fatorDeRisco: 'Controles Internos', horizonte: 'Curto Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'MUD-Processo', diretoria: 'MUD-Diretoria', risco: 'Risco 16', descricaoDoRisco: 'Descrição do Risco 16', dataDeIdentificacao: '2023-01-16', causaRaizDoRisco: 'Causa do Risco 16', consequenciaDoRisco: 'Consequência do Risco 16', processoAfetado: 'Processo Afetado 16', descricaoDoControle: 'Controle do Risco 16', statusDoRisco: 'Mitigado', planoDeAcao: 'PA-016', dataDaUltimaRevisao: '2024-07-16', dataDaProximaRevisao: '2025-01-16', ier: 0, probabilidadeInerente: 'Possível', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Alto', probabilidadeResidual: 'Raro', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Médio' },
  { id: '17', gerencia: 'Suprimentos', topRiskAssociado: 'Risco de Descumprimento 09. I. Operacional', categoriaMP: '8', orig: 4, prob: 9, ctrl: 10, tempo: 10, facil: 4, elev: 705, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Leonardo', v: 5, d: 7.5, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 5, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '9.1 Desempenho', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-SUP-Operacional', tronco: '9.1 Desempenho', englobado: 'Longo Prazo', fatorDeRisco: 'Expansão - Portos e Terminais', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'SUP-Processo', diretoria: 'SUP-Diretoria', risco: 'Risco 17', descricaoDoRisco: 'Descrição do Risco 17', dataDeIdentificacao: '2023-01-17', causaRaizDoRisco: 'Causa do Risco 17', consequenciaDoRisco: 'Consequência do Risco 17', processoAfetado: 'Processo Afetado 17', descricaoDoControle: 'Controle do Risco 17', statusDoRisco: 'Aberto', planoDeAcao: 'PA-017', dataDaUltimaRevisao: '2024-07-17', dataDaProximaRevisao: '2025-01-17', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Menor', nivelDeRiscoInerente: 'Médio', probabilidadeResidual: 'Provável', impactoResidual: 'Insignificante', nivelDeRiscoResidual: 'Baixo' },
  { id: '18', gerencia: 'Ambiental', topRiskAssociado: 'Contaminação de produto (soja/farelo/milho)', categoriaMP: '1', orig: 9, prob: 10, ctrl: 8, tempo: 8, facil: 4, elev: 705, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'TOD', v: 7, d: 7.5, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 7, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Geral', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'E - Ambiental', pilarESG: 'S - Social', indicador: '4.2 Denos', subtema: 'Meio Ambiente', categoriaDoRisco: 'RISK-AMB-Negócio', tronco: '4.2 Denos', englobado: 'Médio Prazo', fatorDeRisco: 'Controles Internos', horizonte: 'Médio Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'AMB-Processo', diretoria: 'AMB-Diretoria', risco: 'Contaminação de produto (soja/farelo/milho)', descricaoDoRisco: 'Risco de contaminação do produto armazenado por agentes externos (pragas, umidade, outros grãos), resultando em perda de qualidade e valor.', dataDeIdentificacao: '2023-01-18', causaRaizDoRisco: 'Falha na vedação de silos, limpeza inadequada, umidade excessiva, pragas.', consequenciaDoRisco: 'Perda de produto, desclassificação de lotes, prejuízo financeiro, dano à reputação.', processoAfetado: 'Armazenagem, Controle de Qualidade', descricaoDoControle: 'Controle do Risco 18', statusDoRisco: 'Em Tratamento', planoDeAcao: 'PA-018', dataDaUltimaRevisao: '2024-07-18', dataDaProximaRevisao: '2025-01-18', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Catastrófico', nivelDeRiscoInerente: 'Extremo', probabilidadeResidual: 'Provável', impactoResidual: 'Maior', nivelDeRiscoResidual: 'Crítico' },
  { id: '19', gerencia: 'Tecnologia', topRiskAssociado: 'Falta de Integridade Risco 07. I. Tecnológico', categoriaMP: '3', orig: 3, prob: 4, ctrl: 4, tempo: 9, facil: 2, elev: 320, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Silvio Hesi', v: 3, d: 3, g: 0, u: 0, t_score: 2, i_score: 0, oredsX: 3, t_rating: 0, riscosAceitaveis: 'sim', riscosNaoAceitaveis: 'não', riscosMix: 'não', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '7.1 Inclusão', subtema: 'Não Aplicável', categoriaDoRisco: 'RISK-TEC-Negócio', tronco: '7.1 Inclusão', englobado: 'Longo Prazo', fatorDeRisco: 'Material Rodante', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'TEC-Processo', diretoria: 'TEC-Diretoria', risco: 'Risco 19', descricaoDoRisco: 'Descrição do Risco 19', dataDeIdentificacao: '2023-01-19', causaRaizDoRisco: 'Causa do Risco 19', consequenciaDoRisco: 'Consequência do Risco 19', processoAfetado: 'Processo Afetado 19', descricaoDoControle: 'Controle do Risco 19', statusDoRisco: 'Fechado', planoDeAcao: 'PA-019', dataDaUltimaRevisao: '2024-07-19', dataDaProximaRevisao: '2025-01-19', ier: 0, probabilidadeInerente: 'Possível', impactoInerente: 'Menor', nivelDeRiscoInerente: 'Médio', probabilidadeResidual: 'Raro', impactoResidual: 'Insignificante', nivelDeRiscoResidual: 'Baixo' },
  { id: '20', gerencia: 'Tecnologia', topRiskAssociado: 'Ausência de Risco 07. I. Tecnológico', categoriaMP: '8', orig: 8, prob: 6, ctrl: 6, tempo: 8, facil: 8, elev: 700, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Silvio Hesi', v: 8, d: 7, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 8, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '7.2 Denos', subtema: 'Governança e Ética', categoriaDoRisco: 'RISK-TEC-Negócio', tronco: '7.2 Denos', englobado: 'Longo Prazo', fatorDeRisco: 'Material Rodante', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'TEC-Processo', diretoria: 'TEC-Diretoria', risco: 'Risco 20', descricaoDoRisco: 'Descrição do Risco 20', dataDeIdentificacao: '2023-01-20', causaRaizDoRisco: 'Causa do Risco 20', consequenciaDoRisco: 'Consequência do Risco 20', processoAfetado: 'Processo Afetado 20', descricaoDoControle: 'Controle do Risco 20', statusDoRisco: 'Mitigado', planoDeAcao: 'PA-020', dataDaUltimaRevisao: '2024-07-20', dataDaProximaRevisao: '2025-01-20', ier: 0, probabilidadeInerente: 'Provável', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Improvável', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Médio' },
  { id: '21', gerencia: 'Tecnologia', topRiskAssociado: 'Dependência de Risco 07. I. Tecnológico', categoriaMP: '7', orig: 7, prob: 8, ctrl: 8, tempo: 7, facil: 8, elev: 700, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Luiz Fernan', v: 7, d: 7.5, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 7, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Negócio', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'E - Ambiental', pilarESG: 'S - Social', indicador: '7.1 Inclusão', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-TEC-Negócio', tronco: '7.1 Inclusão', englobado: 'Longo Prazo', fatorDeRisco: 'Material Rodante', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'TEC-Processo', diretoria: 'TEC-Diretoria', risco: 'Risco 21', descricaoDoRisco: 'Descrição do Risco 21', dataDeIdentificacao: '2023-01-21', causaRaizDoRisco: 'Causa do Risco 21', consequenciaDoRisco: 'Consequência do Risco 21', processoAfetado: 'Processo Afetado 21', descricaoDoControle: 'Controle do Risco 21', statusDoRisco: 'Aberto', planoDeAcao: 'PA-021', dataDaUltimaRevisao: '2024-07-21', dataDaProximaRevisao: '2025-01-21', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Possível', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Alto' },
  { id: '22', gerencia: 'Jurídico', topRiskAssociado: 'Acesso em Risco 05. I. Jurídico', categoriaMP: '10', orig: 10, prob: 4, ctrl: 8, tempo: 8, facil: 8, elev: 690, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Silvio Hesi', v: 10, d: 5, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 10, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Negócio', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'E - Ambiental', pilarESG: 'S - Social', indicador: '5.3 Decisão', subtema: 'Não Aplicável', categoriaDoRisco: 'RISK-JUR-Operacional', tronco: '5.3 Decisão', englobado: 'Longo Prazo', fatorDeRisco: 'Expansão - FMT', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'JUR-Processo', diretoria: 'JUR-Diretoria', risco: 'Risco 22', descricaoDoRisco: 'Descrição do Risco 22', dataDeIdentificacao: '2023-01-22', causaRaizDoRisco: 'Causa do Risco 22', consequenciaDoRisco: 'Consequência do Risco 22', processoAfetado: 'Processo Afetado 22', descricaoDoControle: 'Controle do Risco 22', statusDoRisco: 'Em Tratamento', planoDeAcao: 'PA-022', dataDaUltimaRevisao: '2024-07-22', dataDaProximaRevisao: '2025-01-22', ier: 0, probabilidadeInerente: 'Possível', impactoInerente: 'Catastrófico', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Raro', impactoResidual: 'Maior', nivelDeRiscoResidual: 'Alto' },
  { id: '23', gerencia: 'Tecnologia', topRiskAssociado: 'Gestão de Risco 07. I. Tecnológico', categoriaMP: '6', orig: 8, prob: 6, ctrl: 8, tempo: 6, facil: 8, elev: 675, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Igor Iguti', v: 6, d: 7, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 6, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '7.1 Inclusão', subtema: 'Governança e Ética', categoriaDoRisco: 'RISK-TEC-Negócio', tronco: '7.1 Inclusão', englobado: 'Curto Prazo', fatorDeRisco: 'Material Rodante', horizonte: 'Curto Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'TEC-Processo', diretoria: 'TEC-Diretoria', risco: 'Risco 23', descricaoDoRisco: 'Descrição do Risco 23', dataDeIdentificacao: '2023-01-23', causaRaizDoRisco: 'Causa do Risco 23', consequenciaDoRisco: 'Consequência do Risco 23', processoAfetado: 'Processo Afetado 23', descricaoDoControle: 'Controle do Risco 23', statusDoRisco: 'Fechado', planoDeAcao: 'PA-023', dataDaUltimaRevisao: '2024-07-23', dataDaProximaRevisao: '2025-01-23', ier: 0, probabilidadeInerente: 'Provável', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Improvável', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Médio' },
  { id: '25', gerencia: 'Comercial', topRiskAssociado: 'Entrada de Risco 06. I. Operacional', categoriaMP: '5', orig: 7, prob: 6, ctrl: 6, tempo: 8, facil: 8, elev: 670, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Silvio Hesi', v: 7, d: 8, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 7, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Negócio', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '6.1 Desempenho', subtema: 'Não Aplicável', categoriaDoRisco: 'RISK-COM-Negócio', tronco: '6.1 Desempenho', englobado: 'Longo Prazo', fatorDeRisco: 'Financeiro', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'COM-Processo', diretoria: 'COM-Diretoria', risco: 'Risco 25', descricaoDoRisco: 'Descrição do Risco 25', dataDeIdentificacao: '2023-01-25', causaRaizDoRisco: 'Causa do Risco 25', consequenciaDoRisco: 'Consequência do Risco 25', processoAfetado: 'Processo Afetado 25', descricaoDoControle: 'Controle do Risco 25', statusDoRisco: 'Mitigado', planoDeAcao: 'PA-025', dataDaUltimaRevisao: '2024-07-25', dataDaProximaRevisao: '2025-01-25', ier: 0, probabilidadeInerente: 'Provável', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Improvável', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Médio' },
  { id: '26', gerencia: 'Tecnologia', topRiskAssociado: 'Ausência de Risco 07. I. Operacional', categoriaMP: '8', orig: 8, prob: 8, ctrl: 8, tempo: 9, facil: 4, elev: 665, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Leonardo', v: 6.5, d: 5, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 6.5, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'sim', riscosMix: 'não', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'E - Ambiental', pilarESG: 'S - Social', indicador: '7.1 Inclusão', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-TEC-Negócio', tronco: '7.1 Inclusão', englobado: 'Curto Prazo', fatorDeRisco: 'Tecnologia e Segurança da Informação', horizonte: 'Curto Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'TEC-Processo', diretoria: 'TEC-Diretoria', risco: 'Risco 26', descricaoDoRisco: 'Descrição do Risco 26', dataDeIdentificacao: '2023-01-26', causaRaizDoRisco: 'Causa do Risco 26', consequenciaDoRisco: 'Consequência do Risco 26', processoAfetado: 'Processo Afetado 26', descricaoDoControle: 'Controle do Risco 26', statusDoRisco: 'Aberto', planoDeAcao: 'PA-026', dataDaUltimaRevisao: '2024-07-26', dataDaProximaRevisao: '2025-01-26', ier: 0, probabilidadeInerente: 'Quase Certo', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Crítico', probabilidadeResidual: 'Provável', impactoResidual: 'Moderado', nivelDeRiscoResidual: 'Alto' },
  { id: '27', gerencia: 'Suprimentos', topRiskAssociado: 'Dependência de Risco 09. I. Regulatório', categoriaMP: '7', orig: 7, prob: 4, ctrl: 6, tempo: 10, facil: 4, elev: 665, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Diogo Velo', v: 7.5, d: 2, g: 0, u: 0, t_score: 5, i_score: 0, oredsX: 7.5, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '9.1 Desempenho', subtema: 'Não Aplicável', categoriaDoRisco: 'RISK-SUP-Negócio', tronco: '9.1 Desempenho', englobado: 'Longo Prazo', fatorDeRisco: 'Financeiro', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'SUP-Processo', diretoria: 'SUP-Diretoria', risco: 'Risco 27', descricaoDoRisco: 'Descrição do Risco 27', dataDeIdentificacao: '2023-01-27', causaRaizDoRisco: 'Causa do Risco 27', consequenciaDoRisco: 'Consequência do Risco 27', processoAfetado: 'Processo Afetado 27', descricaoDoControle: 'Controle do Risco 27', statusDoRisco: 'Em Tratamento', planoDeAcao: 'PA-027', dataDaUltimaRevisao: '2024-07-27', dataDaProximaRevisao: '2025-01-27', ier: 0, probabilidadeInerente: 'Possível', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Alto', probabilidadeResidual: 'Raro', impactoResidual: 'Menor', nivelDeRiscoResidual: 'Baixo' },
  { id: '28', gerencia: 'Comercial', topRiskAssociado: 'Mudança de Risco 06. I. Regulatório', categoriaMP: '8', orig: 8, prob: 2, ctrl: 8, tempo: 10, facil: 2, elev: 660, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Guilherme', v: 6.5, d: 4, g: 0, u: 0, t_score: 4, i_score: 0, oredsX: 6.5, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Negócio', tipoDeRisco: 'Risco Prioritário', bowtie: 'Não Realizado', statusControle: 'Ativo', urlDoCC: '', possuiCC: 'Não', pilar: 'S - Social', pilarESG: 'S - Social', indicador: '6.3 Evolução', subtema: 'Não Aplicável', categoriaDoRisco: 'RISK-COM-Negócio', tronco: '6.3 Evolução', englobado: 'Longo Prazo', fatorDeRisco: 'Financeiro', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'COM-Processo', diretoria: 'COM-Diretoria', risco: 'Risco 28', descricaoDoRisco: 'Descrição do Risco 28', dataDeIdentificacao: '2023-01-28', causaRaizDoRisco: 'Causa do Risco 28', consequenciaDoRisco: 'Consequência do Risco 28', processoAfetado: 'Processo Afetado 28', descricaoDoControle: 'Controle do Risco 28', statusDoRisco: 'Fechado', planoDeAcao: 'PA-028', dataDaUltimaRevisao: '2024-07-28', dataDaProximaRevisao: '2025-01-28', ier: 0, probabilidadeInerente: 'Improvável', impactoInerente: 'Maior', nivelDeRiscoInerente: 'Médio', probabilidadeResidual: 'Raro', impactoResidual: 'Menor', nivelDeRiscoResidual: 'Baixo' },
  { id: '29', gerencia: 'Operação', topRiskAssociado: 'Colapso de Risco OLN Operacional', categoriaMP: '8', orig: 6, prob: 4, ctrl: 8, tempo: 8, facil: 4, elev: 660, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Guilherme', v: 4, d: 7, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 4, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Realizado', statusControle: 'Ativo', urlDoCC: 'https://rumo.com/bowtie/29', possuiCC: 'Sim', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '1.3 Paralis', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-OPE-Negócio', tronco: '1.3 Paralis', englobado: 'Longo Prazo', fatorDeRisco: 'Terminais', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'OPE-Processo', diretoria: 'OPE-Diretoria', risco: 'Colapso de estrutura (silo, armazém, torre de elevador, moega)', descricaoDoRisco: 'Risco de colapso total ou parcial de estruturas de armazenagem, podendo levar a perdas massivas de produto, danos a equipamentos e risco à vida.', dataDeIdentificacao: '2023-01-29', causaRaizDoRisco: 'Falha estrutural, sobrecarga, corrosão, fundação inadequada, eventos climáticos extremos.', consequenciaDoRisco: 'Perda total do ativo, fatalidades, interrupção de longo prazo, impacto financeiro severo.', processoAfetado: 'Armazenagem, Manutenção Estrutural', descricaoDoControle: 'Controle do Risco 29', statusDoRisco: 'Mitigado', planoDeAcao: 'PA-029', dataDaUltimaRevisao: '2024-07-29', dataDaProximaRevisao: '2025-01-29', ier: 0, probabilidadeInerente: 'Possível', impactoInerente: 'Moderado', nivelDeRiscoInerente: 'Alto', probabilidadeResidual: 'Raro', impactoResidual: 'Insignificante', nivelDeRiscoResidual: 'Baixo' },
  { id: '30', gerencia: 'Operação', topRiskAssociado: 'Incêndio e Risco OLN Operacional', categoriaMP: '8', orig: 4, ctrl: 4, prob: 4, tempo: 8, facil: 4, elev: 660, estrategia: 'Manter', filho: 'Não', responsavelPeloRisco: 'Guilherme', v: 4, d: 7, g: 0, u: 0, t_score: 7, i_score: 0, oredsX: 4, t_rating: 0, riscosAceitaveis: 'não', riscosNaoAceitaveis: 'não', riscosMix: 'sim', origemDoRisco: 'Técnico', tipoDeRisco: 'Risco Prioritário', bowtie: 'Realizado', statusControle: 'Ativo', urlDoCC: 'https://rumo.com/bowtie/30', possuiCC: 'Sim', pilar: 'G - Governança', pilarESG: 'S - Social', indicador: '1.3 Paralis', subtema: 'Integridade de Ativos', categoriaDoRisco: 'RISK-OPE-Negócio', tronco: '1.3 Paralis', englobado: 'Longo Prazo', fatorDeRisco: 'Segurança do Trabalho', horizonte: 'Longo Prazo', ge: 'Controles Internos', gr: 'Observação', observacao: '', dataDaAvaliacao: '2025-07-15', contexto: '', processo: 'OPE-Processo', diretoria: 'OPE-Diretoria', risco: 'Incêndio e explosão em terminais (silos/ armazéns/ correias transportadoras)', descricaoDoRisco: 'Risco de ignição de poeira em suspensão ou material acumulado, podendo levar a incêndios de grandes proporções ou explosões em ambientes confinados.', dataDeIdentificacao: '2023-01-30', causaRaizDoRisco: 'Fontes de ignição (faíscas, superfícies quentes), acúmulo de poeira combustível, falha em sistemas elétricos.', consequenciaDoRisco: 'Danos severos ao patrimônio, fatalidades, interrupção prolongada da operação.', processoAfetado: 'Operação de Terminais, Manutenção Elétrica e Mecânica', descricaoDoControle: 'Controle do Risco 30', statusDoRisco: 'Aberto', planoDeAcao: 'PA-030', dataDaUltimaRevisao: '2024-07-30', dataDaProximaRevisao: '2025-01-30', ier: 0, probabilidadeInerente: 'Possível', impactoInerente: 'Menor', nivelDeRiscoInerente: 'Médio', probabilidadeResidual: 'Raro', impactoResidual: 'Insignificante', nivelDeRiscoResidual: 'Baixo' }
];

export const kpiData = {
  compliance: {
    value: 92.5,
    change: 1.2,
  },
  overdueItems: {
    value: kpisData.filter(k => k.status === 'Atrasado').length,
    change: -3,
  },
  criticalRisks: {
    value: risksData.filter(r => (r.nivelDeRiscoResidual === 'Crítico' || r.nivelDeRiscoResidual === 'Extremo') && r.possuiCC !== 'Sim').length,
    change: 1,
  },
  controlDeviations: {
    value: controlsData.filter(c => c.status === 'Implementado com Pendência').length,
    change: 2,
  },
};

export const complianceChartData = [
  { month: 'Jan', compliance: 88, target: 90 },
  { month: 'Feb', compliance: 91, target: 90 },
  { month: 'Mar', compliance: 92, target: 90 },
  { month: 'Apr', compliance: 89, target: 90 },
  { month: 'May', compliance: 93, target: 90 },
  { month: 'Jun', compliance: 95, target: 90 },
  { month: 'Jul', compliance: 92.5, target: 90 },
];

export const recentActivityData: RecentActivity[] = [
    {
        id: '1',
        user: { name: 'Alice Johnson', avatarUrl: 'https://picsum.photos/seed/101/32/32' },
        action: 'criou um novo risco',
        target: 'Falha no sistema de freios',
        timestamp: '2 horas atrás',
    },
    {
        id: '2',
        user: { name: 'Bob Williams', avatarUrl: 'https://picsum.photos/seed/102/32/32' },
        action: 'atualizou o controle',
        target: 'Inspeção de via semanal',
        timestamp: '5 horas atrás',
    },
    {
        id: '3',
        user: { name: 'Carla Davis', avatarUrl: 'https://picsum.photos/seed/103/32/32' },
        action: 'aprovou o risco',
        target: 'Descarrilamento em pátio',
        timestamp: '1 dia atrás',
    },
    {
        id: '4',
        user: { name: 'David Miller', avatarUrl: 'https://picsum.photos/seed/104/32/32' },
        action: 'comentou no KPI',
        target: '% de conformidade de inspeção',
        timestamp: '2 dias atrás',
    },
];

const getStatusCounts = (risks: Risk[]) => {
  const counts: { [key: string]: number } = {
    'Aberto': 0,
    'Em Tratamento': 0,
    'Fechado': 0,
    'Mitigado': 0,
  };
  risks.forEach(risk => {
    const status = risk.statusDoRisco;
    if (counts.hasOwnProperty(status)) {
      counts[status]++;
    }
  });
  return counts;
};

const statusCounts = getStatusCounts(risksData);

export const statusBreakdownChartData = [
  { name: 'Aberto', value: statusCounts['Aberto'], fill: 'hsl(var(--chart-2))' },
  { name: 'Em Tratamento', value: statusCounts['Em Tratamento'], fill: 'hsl(var(--chart-1))' },
  { name: 'Mitigado', value: statusCounts['Mitigado'], fill: 'hsl(var(--chart-3))' },
  { name: 'Fechado', value: statusCounts['Fechado'], fill: 'hsl(var(--muted-foreground))' },
];

export const initialBowtieData: BowtieData[] = [
    {
        id: 'B001',
        riskId: '29',
        topEvent: {
            title: "Colapso de estrutura",
            description: "Processo de armazenamento"
        },
        threats: [
            { 
                id: 'T1', 
                title: 'Sobrecarga da estrutura',
                barriers: [
                    { id: 'B1-1', title: 'Controle de Peso', responsible: 'Operação', effectiveness: 'Eficaz', status: 'Implementado' },
                ]
            },
        ],
        consequences: [
            {
                id: 'C1',
                title: 'Perda de material',
                barriers: [
                    { id: 'B3-1', title: 'Seguro Patrimonial', responsible: 'Financeiro', effectiveness: 'Eficaz', status: 'Implementado' },
                ]
            },
        ]
    }
];

export const getEmptyBowtie = (risk?: Risk): BowtieData => {
    const newId = `B${Math.random().toString(36).substr(2, 9)}`;
    const newThreat: BowtieThreat = {
        id: 'T1',
        title: 'Nova Ameaça',
        barriers: [{
            id: 'B1-1',
            title: 'Nova Barreira Preventiva',
            responsible: 'Indefinido',
            effectiveness: 'Eficaz',
            status: 'Pendente'
        }]
    };
     const newConsequence: BowtieConsequence = {
        id: 'C1',
        title: 'Nova Consequência',
        barriers: [{
            id: 'B2-1',
            title: 'Nova Barreira Mitigatória',
            responsible: 'Indefinido',
            effectiveness: 'Eficaz',
            status: 'Pendente'
        }]
    };

    if (!risk) {
        return {
            id: newId,
            riskId: `R-GENERIC-${newId}`,
            topEvent: {
                title: 'Novo Evento de Topo',
                description: 'Descreva o processo',
            },
            threats: [newThreat],
            consequences: [newConsequence],
        };
    }

    return {
        id: newId,
        riskId: risk.id,
        topEvent: {
            title: risk.risco,
            description: risk.processoAfetado,
        },
        threats: [newThreat],
        consequences: [newConsequence],
    };
};
